# V13 Structural Tail Residual: Iteration 1

## Research question

V12 demonstrated that a predictor-only case-adaptive gain nearly reaches the
non-deployable oracle gain, but still does not pass the all-development P99
underprediction gate. This rules out scalar gain calibration as the main
remaining bottleneck.

V13 therefore freezes the V11 global-gain-0.90 predictor and searches for one
additional predictor-only, zero-case-mean local residual formula. The target
is the signed complete-case V11 residual divided by the frozen V10 stress
scale. The residual is centered over every complete case so it cannot silently
replace the existing case-mean model.

Search discovery uses 5,000 deterministic rows per training case with stronger
P95/P99 exposure. Formula selection uses all 400,360 elements of each of the 15
validation cases. The selected candidate is evaluated on all elements of the
15 internal cases and all 119 training cases for a 149-case development audit.
The 50 final-test files are inventoried but never read.

## 1. Imports and package root

In [1]:
from pathlib import Path
import json
import sys

import pandas as pd

try:
    from IPython.display import display
except Exception:
    display = print


def resolve_package_root() -> Path:
    current = Path.cwd().resolve()
    for candidate in [current, *current.parents]:
        if (candidate / "src" / "v13_structural_tail_residual.py").exists():
            return candidate
    raise FileNotFoundError("Could not locate the NotebookCT3 package root.")


PACKAGE_ROOT = resolve_package_root()
if str(PACKAGE_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(PACKAGE_ROOT / "src"))

from v13_structural_tail_residual import (
    V13Config,
    output_directory,
    preflight_v13,
    run_v13_pilot,
)

print("Package root:", PACKAGE_ROOT)
print("Python:", sys.executable)

Package root: /net/scratch/j96317yn/NotebookCT3
Python: /net/scratch/j96317yn/NotebookCT3/.venv/bin/python

## 2. Locked V13 configuration

In [2]:
RUN_V13_PILOT = True

CONFIG = V13Config(
    iteration=1,
    output_subdir="iteration_1",
    rows_per_training_case=5_000,
    total_niterations=1_000,
    populations=8,
    segment_niterations=100,
    population_size=40,
    ncycles_per_iteration=100,
    batch_size=50_000,
    maxsize=36,
    maxdepth=11,
    julia_threads=8,
    no_activity_timeout_seconds=45 * 60,
    segment_wall_timeout_seconds=3 * 60 * 60,
    watchdog_poll_seconds=60,
    max_attempts_per_segment=3,
    max_candidates_for_full_validation=24,
    force_rebuild_training_cache=False,
    minimum_validation_rmse_improvement_fraction=0.005,
    maximum_p95_degradation_absolute=0.010,
    maximum_all149_p95_degradation_absolute=0.005,
    maximum_p99_relative_error=0.15,
    maximum_p99_underprediction=0.10,
    minimum_top1_hotspot_overlap=0.60,
    minimum_top1_recall_in_predicted_top5=0.80,
)

OUTPUT_DIR = output_directory(PACKAGE_ROOT, CONFIG)
display(pd.DataFrame([CONFIG.__dict__]).T.rename(columns={0: "value"}))
print("Output directory:", OUTPUT_DIR)
print("Recoverable segments:", CONFIG.n_segments)
print("Population iterations:", CONFIG.population_iterations_total)

                                                    value
iteration                                               1
output_subdir                                 iteration_1
rows_per_training_case                               5000
total_niterations                                    1000
populations                                             8
segment_niterations                                   100
population_size                                        40
ncycles_per_iteration                                 100
batch_size                                          50000
maxsize                                                36
maxdepth                                               11
julia_threads                                           8
no_activity_timeout_seconds                          2700
segment_wall_timeout_seconds                        10800
watchdog_poll_seconds                                  60
max_attempts_per_segment                                3
max_candidates_for_full_validation                     24
force_rebuild_training_cache                        False
minimum_validation_rmse_improvement_fraction        0.005
maximum_p95_degradation_absolute                     0.01
maximum_all149_p95_degradation_absolute             0.005
maximum_p99_relative_error                           0.15
maximum_p99_underprediction                           0.1
minimum_top1_hotspot_overlap                          0.6
minimum_top1_recall_in_predicted_top5                 0.8

Output directory: /net/scratch/j96317yn/NotebookCT3/outputs/15_v13_structural_tail_residual/iteration_1
Recoverable segments: 10
Population iterations: 8000

## 3. Frozen-input preflight

Preflight hashes the exact V11 and V12 artifacts, confirms the V12 decision to
retain V11 gain 0.90, verifies the frozen 119/15/15/50 manifest and records the
50 final case identifiers without opening their element files.

In [3]:
PREFLIGHT = preflight_v13(PACKAGE_ROOT, CONFIG)
display(PREFLIGHT["checks"])
print("Frozen artifacts hashed:", len(PREFLIGHT["hash_audit"]))
print("Training cases:", len(PREFLIGHT["inputs"]["train_ids"]))
print("Validation cases:", len(PREFLIGHT["inputs"]["validation_ids"]))
print("Internal development cases:", len(PREFLIGHT["inputs"]["internal_ids"]))
print("Sealed final-test cases:", len(PREFLIGHT["inputs"]["final_ids"]))

,check,value,expected,pass
0,training_cases,119,119,True
1,validation_cases,15,15,True
2,internal_test_cases,15,15,True
3,development_cases,149,149,True
4,sealed_final_cases,50,50,True
5,v12_complete,complete,complete,True
6,v12_final_cases_read,0,0,True
7,v12_retains_v11,retain_v11_global_gain_0_90,retain_v11_global_gain_0_90,True
8,frozen_v11_gain,0.9,0.9,True
9,v13_features,42,42,True
10,recoverable_segments,10,10,True
11,population_iterations,8000,8000,True

Frozen artifacts hashed: 18
Training cases: 119
Validation cases: 15
Internal development cases: 15
Sealed final-test cases: 50

## 4. Run or resume V13

Training-case sample preparation is cached one complete case at a time. The
PySR search is divided into ten checkpointed segments. Re-running this cell
reuses every valid case cache and completed segment. A watchdog stops inactive
workers and resumes from the last stable checkpoint.

In [4]:
RESULT = None
if RUN_V13_PILOT:
    RESULT = run_v13_pilot(PACKAGE_ROOT, CONFIG)
    display(pd.DataFrame([RESULT]))
else:
    print("V13 pilot skipped because RUN_V13_PILOT=False.")

[1/119] V13 deterministic training sample: case_01

[2/119] V13 deterministic training sample: case_10

[3/119] V13 deterministic training sample: case_11

[4/119] V13 deterministic training sample: case_12

[5/119] V13 deterministic training sample: case_13

[6/119] V13 deterministic training sample: case_14

[7/119] V13 deterministic training sample: case_15

[8/119] V13 deterministic training sample: case_16

[9/119] V13 deterministic training sample: case_17

[10/119] V13 deterministic training sample: case_19

[11/119] V13 deterministic training sample: case_20

[12/119] V13 deterministic training sample: case_21

[13/119] V13 deterministic training sample: case_24

[14/119] V13 deterministic training sample: case_27

[15/119] V13 deterministic training sample: case_32

[16/119] V13 deterministic training sample: case_34

[17/119] V13 deterministic training sample: case_35

[18/119] V13 deterministic training sample: case_36

[19/119] V13 deterministic training sample: case_39

[20/119] V13 deterministic training sample: case_40

[21/119] V13 deterministic training sample: case_42

[22/119] V13 deterministic training sample: case_43

[23/119] V13 deterministic training sample: case_44

[24/119] V13 deterministic training sample: case_47

[25/119] V13 deterministic training sample: case_48

[26/119] V13 deterministic training sample: case_49

[27/119] V13 deterministic training sample: case_52

[28/119] V13 deterministic training sample: case_56

[29/119] V13 deterministic training sample: case_58

[30/119] V13 deterministic training sample: case_59

[31/119] V13 deterministic training sample: case_61

[32/119] V13 deterministic training sample: case_63

[33/119] V13 deterministic training sample: case_64

[34/119] V13 deterministic training sample: case_67

[35/119] V13 deterministic training sample: case_68

[36/119] V13 deterministic training sample: case_69

[37/119] V13 deterministic training sample: case_72

[38/119] V13 deterministic training sample: case_73

[39/119] V13 deterministic training sample: case_74

[40/119] V13 deterministic training sample: case_75

[41/119] V13 deterministic training sample: case_77

[42/119] V13 deterministic training sample: case_78

[43/119] V13 deterministic training sample: case_79

[44/119] V13 deterministic training sample: case_84

[45/119] V13 deterministic training sample: case_85

[46/119] V13 deterministic training sample: case_89

[47/119] V13 deterministic training sample: case_91

[48/119] V13 deterministic training sample: case_92

[49/119] V13 deterministic training sample: case_94

[50/119] V13 deterministic training sample: case_95

[51/119] V13 deterministic training sample: case_96

[52/119] V13 deterministic training sample: case_97

[53/119] V13 deterministic training sample: case_99

[54/119] V13 deterministic training sample: case_100

[55/119] V13 deterministic training sample: case_104

[56/119] V13 deterministic training sample: case_105

[57/119] V13 deterministic training sample: case_106

[58/119] V13 deterministic training sample: case_107

[59/119] V13 deterministic training sample: case_109

[60/119] V13 deterministic training sample: case_110

[61/119] V13 deterministic training sample: case_111

[62/119] V13 deterministic training sample: case_114

[63/119] V13 deterministic training sample: case_115

[64/119] V13 deterministic training sample: case_116

[65/119] V13 deterministic training sample: case_118

[66/119] V13 deterministic training sample: case_119

[67/119] V13 deterministic training sample: case_121

[68/119] V13 deterministic training sample: case_122

[69/119] V13 deterministic training sample: case_124

[70/119] V13 deterministic training sample: case_125

[71/119] V13 deterministic training sample: case_127

[72/119] V13 deterministic training sample: case_128

[73/119] V13 deterministic training sample: case_129

[74/119] V13 deterministic training sample: case_130

[75/119] V13 deterministic training sample: case_133

[76/119] V13 deterministic training sample: case_136

[77/119] V13 deterministic training sample: case_137

[78/119] V13 deterministic training sample: case_139

[79/119] V13 deterministic training sample: case_141

[80/119] V13 deterministic training sample: case_142

[81/119] V13 deterministic training sample: case_143

[82/119] V13 deterministic training sample: case_144

[83/119] V13 deterministic training sample: case_146

[84/119] V13 deterministic training sample: case_148

[85/119] V13 deterministic training sample: case_150

[86/119] V13 deterministic training sample: case_151

[87/119] V13 deterministic training sample: case_153

[88/119] V13 deterministic training sample: case_154

[89/119] V13 deterministic training sample: case_155

[90/119] V13 deterministic training sample: case_156

[91/119] V13 deterministic training sample: case_157

[92/119] V13 deterministic training sample: case_158

[93/119] V13 deterministic training sample: case_163

[94/119] V13 deterministic training sample: case_164

[95/119] V13 deterministic training sample: case_165

[96/119] V13 deterministic training sample: case_166

[97/119] V13 deterministic training sample: case_169

[98/119] V13 deterministic training sample: case_170

[99/119] V13 deterministic training sample: case_171

[100/119] V13 deterministic training sample: case_173

[101/119] V13 deterministic training sample: case_175

[102/119] V13 deterministic training sample: case_179

[103/119] V13 deterministic training sample: case_180

[104/119] V13 deterministic training sample: case_181

[105/119] V13 deterministic training sample: case_182

[106/119] V13 deterministic training sample: case_183

[107/119] V13 deterministic training sample: case_184

[108/119] V13 deterministic training sample: case_185

[109/119] V13 deterministic training sample: case_186

[110/119] V13 deterministic training sample: case_187

[111/119] V13 deterministic training sample: case_188

[112/119] V13 deterministic training sample: case_189

[113/119] V13 deterministic training sample: case_190

[114/119] V13 deterministic training sample: case_191

[115/119] V13 deterministic training sample: case_192

[116/119] V13 deterministic training sample: case_193

[117/119] V13 deterministic training sample: case_194

[118/119] V13 deterministic training sample: case_195

[119/119] V13 deterministic training sample: case_200

V13 segment 1/10, attempt 1: fresh search

V13 segment 1, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=False

V13 segment 1, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V13 segment 1, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V13 segment 1: complete; planned cumulative 800/8000

V13 segment 2/10, attempt 1: checkpoint resume

V13 segment 2, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V13 segment 2, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V13 segment 2, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V13 segment 2: complete; planned cumulative 1600/8000

V13 segment 3/10, attempt 1: checkpoint resume

V13 segment 3, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V13 segment 3, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V13 segment 3, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V13 segment 3: complete; planned cumulative 2400/8000

V13 segment 4/10, attempt 1: checkpoint resume

V13 segment 4, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V13 segment 4, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V13 segment 4, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V13 segment 4: complete; planned cumulative 3200/8000

V13 segment 5/10, attempt 1: checkpoint resume

V13 segment 5, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V13 segment 5, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V13 segment 5, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V13 segment 5: complete; planned cumulative 4000/8000

V13 segment 6/10, attempt 1: checkpoint resume

V13 segment 6, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V13 segment 6, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V13 segment 6, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V13 segment 6: complete; planned cumulative 4800/8000

V13 segment 7/10, attempt 1: checkpoint resume

V13 segment 7, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V13 segment 7, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V13 segment 7, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V13 segment 7: complete; planned cumulative 5600/8000

V13 segment 8/10, attempt 1: checkpoint resume

V13 segment 8, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V13 segment 8, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V13 segment 8, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V13 segment 8: complete; planned cumulative 6400/8000

V13 segment 9/10, attempt 1: checkpoint resume

V13 segment 9, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V13 segment 9, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V13 segment 9, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V13 segment 9: complete; planned cumulative 7200/8000

V13 segment 10/10, attempt 1: checkpoint resume

V13 segment 10, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V13 segment 10, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V13 segment 10, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V13 segment 10: complete; planned cumulative 8000/8000

[1/15] validation complete-case V13: case_18

[2/15] validation complete-case V13: case_29

[3/15] validation complete-case V13: case_45

[4/15] validation complete-case V13: case_51

[5/15] validation complete-case V13: case_54

[6/15] validation complete-case V13: case_60

[7/15] validation complete-case V13: case_62

[8/15] validation complete-case V13: case_81

[9/15] validation complete-case V13: case_83

[10/15] validation complete-case V13: case_86

[11/15] validation complete-case V13: case_87

[12/15] validation complete-case V13: case_101

[13/15] validation complete-case V13: case_120

[14/15] validation complete-case V13: case_145

[15/15] validation complete-case V13: case_176

[1/15] internal_test complete-case V13: case_06

/net/scratch/j96317yn/NotebookCT3/src/v13_structural_tail_residual.py:1101: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False False False False False False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v13_structural_tail_residual.py:1101: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True False False False False False False False False False
 False False False False False False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v13_structural_tail_residual.py:1101: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True False False False False False False False False False False False
 False False False False False False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v13_structural_tail_residual.py:1101: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v13_structural_tail_residual.py:1101: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v13_structural_tail_residual.py:1101: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True False False False  True  True False False False  True
  True  True  True  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v13_structural_tail_residual.py:1101: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v13_structural_tail_residual.py:1101: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v13_structural_tail_residual.py:1101: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False False False False False False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid

[2/15] internal_test complete-case V13: case_28

[3/15] internal_test complete-case V13: case_57

[4/15] internal_test complete-case V13: case_66

[5/15] internal_test complete-case V13: case_71

[6/15] internal_test complete-case V13: case_82

[7/15] internal_test complete-case V13: case_93

[8/15] internal_test complete-case V13: case_98

[9/15] internal_test complete-case V13: case_102

[10/15] internal_test complete-case V13: case_117

[11/15] internal_test complete-case V13: case_147

[12/15] internal_test complete-case V13: case_159

[13/15] internal_test complete-case V13: case_196

[14/15] internal_test complete-case V13: case_197

[15/15] internal_test complete-case V13: case_199

[1/119] train complete-case V13: case_01

[2/119] train complete-case V13: case_10

[3/119] train complete-case V13: case_11

[4/119] train complete-case V13: case_12

[5/119] train complete-case V13: case_13

[6/119] train complete-case V13: case_14

[7/119] train complete-case V13: case_15

[8/119] train complete-case V13: case_16

[9/119] train complete-case V13: case_17

[10/119] train complete-case V13: case_19

[11/119] train complete-case V13: case_20

[12/119] train complete-case V13: case_21

[13/119] train complete-case V13: case_24

[14/119] train complete-case V13: case_27

[15/119] train complete-case V13: case_32

[16/119] train complete-case V13: case_34

[17/119] train complete-case V13: case_35

[18/119] train complete-case V13: case_36

[19/119] train complete-case V13: case_39

[20/119] train complete-case V13: case_40

[21/119] train complete-case V13: case_42

[22/119] train complete-case V13: case_43

[23/119] train complete-case V13: case_44

[24/119] train complete-case V13: case_47

[25/119] train complete-case V13: case_48

[26/119] train complete-case V13: case_49

[27/119] train complete-case V13: case_52

[28/119] train complete-case V13: case_56

[29/119] train complete-case V13: case_58

[30/119] train complete-case V13: case_59

[31/119] train complete-case V13: case_61

[32/119] train complete-case V13: case_63

[33/119] train complete-case V13: case_64

[34/119] train complete-case V13: case_67

[35/119] train complete-case V13: case_68

[36/119] train complete-case V13: case_69

[37/119] train complete-case V13: case_72

[38/119] train complete-case V13: case_73

[39/119] train complete-case V13: case_74

[40/119] train complete-case V13: case_75

[41/119] train complete-case V13: case_77

[42/119] train complete-case V13: case_78

[43/119] train complete-case V13: case_79

[44/119] train complete-case V13: case_84

[45/119] train complete-case V13: case_85

[46/119] train complete-case V13: case_89

[47/119] train complete-case V13: case_91

[48/119] train complete-case V13: case_92

[49/119] train complete-case V13: case_94

[50/119] train complete-case V13: case_95

[51/119] train complete-case V13: case_96

[52/119] train complete-case V13: case_97

[53/119] train complete-case V13: case_99

[54/119] train complete-case V13: case_100

[55/119] train complete-case V13: case_104

[56/119] train complete-case V13: case_105

[57/119] train complete-case V13: case_106

[58/119] train complete-case V13: case_107

[59/119] train complete-case V13: case_109

[60/119] train complete-case V13: case_110

[61/119] train complete-case V13: case_111

[62/119] train complete-case V13: case_114

[63/119] train complete-case V13: case_115

[64/119] train complete-case V13: case_116

[65/119] train complete-case V13: case_118

[66/119] train complete-case V13: case_119

[67/119] train complete-case V13: case_121

[68/119] train complete-case V13: case_122

[69/119] train complete-case V13: case_124

[70/119] train complete-case V13: case_125

[71/119] train complete-case V13: case_127

[72/119] train complete-case V13: case_128

[73/119] train complete-case V13: case_129

[74/119] train complete-case V13: case_130

[75/119] train complete-case V13: case_133

[76/119] train complete-case V13: case_136

[77/119] train complete-case V13: case_137

[78/119] train complete-case V13: case_139

[79/119] train complete-case V13: case_141

[80/119] train complete-case V13: case_142

[81/119] train complete-case V13: case_143

[82/119] train complete-case V13: case_144

[83/119] train complete-case V13: case_146

[84/119] train complete-case V13: case_148

[85/119] train complete-case V13: case_150

[86/119] train complete-case V13: case_151

[87/119] train complete-case V13: case_153

[88/119] train complete-case V13: case_154

[89/119] train complete-case V13: case_155

[90/119] train complete-case V13: case_156

[91/119] train complete-case V13: case_157

[92/119] train complete-case V13: case_158

[93/119] train complete-case V13: case_163

[94/119] train complete-case V13: case_164

[95/119] train complete-case V13: case_165

[96/119] train complete-case V13: case_166

[97/119] train complete-case V13: case_169

[98/119] train complete-case V13: case_170

[99/119] train complete-case V13: case_171

[100/119] train complete-case V13: case_173

[101/119] train complete-case V13: case_175

[102/119] train complete-case V13: case_179

[103/119] train complete-case V13: case_180

[104/119] train complete-case V13: case_181

[105/119] train complete-case V13: case_182

[106/119] train complete-case V13: case_183

[107/119] train complete-case V13: case_184

[108/119] train complete-case V13: case_185

[109/119] train complete-case V13: case_186

[110/119] train complete-case V13: case_187

[111/119] train complete-case V13: case_188

[112/119] train complete-case V13: case_189

[113/119] train complete-case V13: case_190

[114/119] train complete-case V13: case_191

[115/119] train complete-case V13: case_192

[116/119] train complete-case V13: case_193

[117/119] train complete-case V13: case_194

[118/119] train complete-case V13: case_195

[119/119] train complete-case V13: case_200

,status,iteration,prototype_only,parent_model,train_cases,validation_cases,internal_test_cases,development_cases_evaluated,final_test_cases_read,training_rows,planned_population_iterations,completed_segments,selected_candidate_index,selection_pool_status,promotion_status,failed_promotion_gates,elapsed_seconds,output_directory
0,complete,1,True,v11_global_gain_0_90,119,15,15,149,0,595000,8000,10,2,diagnostic_finite_candidates,retain_v11_global_gain_0_90,[validation_candidate_passes_all_predeclared_g...,8999.594858,/net/scratch/j96317yn/NotebookCT3/outputs/15_v...

## 5. Saved development evidence

In [5]:
artifacts = {
    "completion": OUTPUT_DIR / "v13_complete.json",
    "decision": OUTPUT_DIR / "v13_promotion_decision.json",
    "gates": OUTPUT_DIR / "v13_promotion_gates.csv",
    "scope_metrics": OUTPUT_DIR / "v13_scope_metrics.csv",
    "case_registry": OUTPUT_DIR / "v13_case_failure_registry.csv",
    "candidate_formula": OUTPUT_DIR / "v13_candidate_formula.txt",
    "selected_formula": OUTPUT_DIR / "selected_deployment_formula.txt",
    "candidate_metrics": OUTPUT_DIR / "stages" / "stage_structural_residual" / "candidate_validation_metrics.csv",
    "progress": OUTPUT_DIR / "stages" / "stage_structural_residual" / "search_progress.json",
}
for name, path in artifacts.items():
    print(f"{name:20s} exists={path.exists()}  {path}")

if artifacts["scope_metrics"].exists():
    display(pd.read_csv(artifacts["scope_metrics"]))
if artifacts["gates"].exists():
    display(pd.read_csv(artifacts["gates"]))
if artifacts["decision"].exists():
    print(json.dumps(json.loads(artifacts["decision"].read_text()), indent=2))
if artifacts["selected_formula"].exists():
    print("\n" + artifacts["selected_formula"].read_text(encoding="utf-8"))

completion           exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/15_v13_structural_tail_residual/iteration_1/v13_complete.json
decision             exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/15_v13_structural_tail_residual/iteration_1/v13_promotion_decision.json
gates                exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/15_v13_structural_tail_residual/iteration_1/v13_promotion_gates.csv
scope_metrics        exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/15_v13_structural_tail_residual/iteration_1/v13_scope_metrics.csv
case_registry        exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/15_v13_structural_tail_residual/iteration_1/v13_case_failure_registry.csv
candidate_formula    exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/15_v13_structural_tail_residual/iteration_1/v13_candidate_formula.txt
selected_formula     exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/15_v13_structural_tail_residual/iteration_1/selected_deployment_formula.txt
candidate_metrics    exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/15_v13_structural_tail_residual/iteration_1/stages/stage_structural_residual/candidate_validation_metrics.csv
progress             exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/15_v13_structural_tail_residual/iteration_1/stages/stage_structural_residual/search_progress.json

,iteration,split,model,n_cases,n_elements_evaluated,micro_mae,micro_rmse,micro_r2,macro_mae,macro_rmse,...,mean_top5_actual_rmse,mean_top5_actual_bias,mean_p95_relative_error,mean_p95_underprediction_fraction,mean_p99_relative_error,mean_p99_underprediction_fraction,mean_top5pct_hotspot_overlap,mean_top1pct_hotspot_overlap,mean_top1_recall_in_predicted_top5,max_prediction_abs_max_ratio
0,1,internal_test,v11_global_gain_0_90,15,6005400,1.312537,1.844602,0.600115,1.312537,1.817803,...,3.296655,-1.599205,0.040414,0.000485,0.124700,0.118171,0.588347,0.576757,0.882018,1.584976
1,1,internal_test,v13_structural_tail_residual,15,6005400,1.625743,2.204495,0.428853,1.625743,2.148163,...,2.842087,-0.619778,0.145058,0.000000,0.056730,0.024678,0.598328,0.600616,0.917699,1.368839
2,1,train,v11_global_gain_0_90,119,47642840,1.196211,1.703422,0.629085,1.196211,1.667568,...,3.099323,-1.693312,0.038829,0.003359,0.135189,0.132781,0.578520,0.588004,0.880777,1.543172
3,1,train,v13_structural_tail_residual,119,47642840,1.459595,2.002589,0.487358,1.459595,1.940445,...,2.634458,-0.829380,0.130637,0.000000,0.058898,0.037383,0.589641,0.614457,0.915412,1.341105
4,1,validation,v11_global_gain_0_90,15,6005400,1.228952,1.769763,0.652403,1.228952,1.731626,...,2.990331,-1.396082,0.077506,0.001988,0.102731,0.088884,0.571915,0.600516,0.881652,1.131529
5,1,validation,v13_structural_tail_residual,15,6005400,1.508959,2.074353,0.522459,1.508959,2.023615,...,2.582085,-0.472103,0.175372,0.000000,0.074360,0.011731,0.582096,0.628571,0.916417,0.994618
6,1,all_149_development,v11_global_gain_0_90,149,59653640,1.211217,1.724897,0.629014,1.211217,1.689141,...,3.108216,-1.653916,0.042882,0.002932,0.130866,0.126891,0.578844,0.588132,0.880990,1.584976
7,1,all_149_development,v13_structural_tail_residual,149,59653640,1.481291,2.031091,0.485612,1.481291,1.969729,...,2.650088,-0.772312,0.136592,0.000000,0.060236,0.033521,0.589756,0.614485,0.915744,1.368839

,gate,pass,observed,criterion
0,validation_candidate_passes_all_predeclared_gates,False,False,True
1,internal_test_macro_rmse,False,-0.18173594587640657,-0.005
2,internal_test_p95_preserved,False,0.14505794446306555,0.0504137914205892
3,internal_test_p99_relative_error,True,0.05672978425132023,0.15
4,internal_test_p99_underprediction,True,0.02467816653319425,0.1
5,internal_test_top1_hotspot_overlap,True,0.6006160506160506,0.6
6,internal_test_top1_recall,True,0.9176989676989676,0.8
7,internal_test_numerical_guardrail,True,1.3688390459575615,1.6642248751381932
8,all_149_development_macro_rmse,False,-0.16611264849607554,0.005
9,all_149_development_p95_preserved,False,0.1365919415737178,0.04788225696405078
10,all_149_development_p99_relative_error,True,0.06023621523820106,0.15
11,all_149_development_p99_underprediction,True,0.03352138785246306,0.1
12,all_149_development_top1_hotspot_overlap,True,0.6144845087798109,0.6
13,all_149_development_top1_recall,True,0.9157436523208333,0.8
14,all_149_development_numerical_guardrail,True,1.3688390459575615,1.6642248751381932

{
  "promotion_status": "retain_v11_global_gain_0_90",
  "all_gates_pass": false,
  "failed_gates": [
    "validation_candidate_passes_all_predeclared_gates",
    "internal_test_macro_rmse",
    "internal_test_p95_preserved",
    "all_149_development_macro_rmse",
    "all_149_development_p95_preserved"
  ],
  "selected_candidate_index": 2,
  "selection_pool_status": "diagnostic_finite_candidates",
  "final_test_cases_read": 0
}

V13 did not pass every predeclared development gate.
The frozen V11 global-gain-0.90 formula remains selected.

sigma_selected = ((-0.0116301024532845*temperature_mean + 0.0470427355318997*temperature_p95 - 3.16087946558646*weight_loss_rate_mean + 0.103449215368151*z_max - 0.870195660324862*Abs(4.60760803334225*fluence_rate_p95 - 20.3572633494299) - 100.195330145459) + exp(-1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276) * ((1.10317833861391*(0.55673575*(0.0509611749551904*rho - 9.32241465638866)*(0.0509611749551904*rho - 8.66867535638866) - 31.9731949759449*(theta_cos - 0.922666019258146)**2)*(Abs(0.0509611749551904*rho - 8.59575422638866) - 2.4201684) + 0.285739561816426) + (0.0005298607274781943*z + 0.17657582192765694*(6.3559467282562*nearest_axial_boundary_fraction_proxy - 1.50570424883607)*(-7.28799975835273*nearest_radial_boundary_fraction_proxy + 0.0517386902634747*rho - 6.047025771972898) - 0.24332347927944745 + 0.793705512144892*exp(-9.5925971595468041*(6.3559467282562*nearest_axial_boundary_fraction_proxy - 0.043846887113135693)**2)) + (0.687707530043104*(3.752650699651312*nearest_angular_boundary_fraction_proxy + 7.28799975835273*nearest_radial_boundary_fraction_proxy - 3.560078810528026 + 0.2777422381074965)*(-0.44608657163711589*fluence_rate_mean - 1.291571739959816*nearest_angular_boundary_fraction_proxy + 0.66354475675260838*theta_fraction_proxy + 0.14984744098602391*Abs(-7.28799975835273*nearest_radial_boundary_fraction_proxy + 2.40848321928096*signed_radial_position_proxy + 2.08439162588874) - 0.07467188916362873 + 1.6933224087437673) + 0.0275995197448158))) + ((-1.052449007433797) + (0.1552525042004941)*fluence_rate_mean + (0.07199435596858993)*fluence_rate_p95 + (0.0001133709738926737)*temperature_mean + (-0.001931509820148126)*temperature_p95 + (0.3846993631715923)*weight_loss_rate_mean + (6.817702583133652)*weight_loss_rate_std) + (0.9) * exp(-1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276) * ((1.2093601333202474*(-0.16122678679851166 + exp(-92.749309109240237*(0.3382200152451777 - 2.08887119255503*signed_angular_position_proxy)**2))*(7.68957066477673*nearest_angular_boundary_fraction_proxy - 2.27807624632193)*(7.38407920683658*nearest_radial_boundary_fraction_proxy + Abs(7.38407920683658*nearest_radial_boundary_fraction_proxy - 2.57458268534255) - 2.57458268534255) + 0.19743823997123105) - case_mean(1.2093601333202474*(-0.16122678679851166 + exp(-92.749309109240237*(0.3382200152451777 - 2.08887119255503*signed_angular_position_proxy)**2))*(7.68957066477673*nearest_angular_boundary_fraction_proxy - 2.27807624632193)*(7.38407920683658*nearest_radial_boundary_fraction_proxy + Abs(7.38407920683658*nearest_radial_boundary_fraction_proxy - 2.57458268534255) - 2.57458268534255) + 0.19743823997123105))

## Interpretation boundary

V13 is promoted only if its validation candidate passes every locked gate and
the same frozen candidate is then confirmed on the internal-development and
all-149 scopes. A failed gate automatically retains V11 gain 0.90. Neither a
diagnostic V13 formula nor a small isolated metric improvement is sufficient
to open the final-test set.