# Formal V11 Symbolic Regression: Iteration 4

This notebook runs one complete frozen development rotation:

1. V10 signed staged residual symbolic search, using the Iteration-4
   119 training cases and 595,000 stratified discovery rows;
2. V11 case-mean calibration and tail-aware localised symbolic search;
3. validation-only scalar gain selection, followed by one internal-test audit.

Every complete validation and internal-test case is evaluated. The 50 final
test case names are inventoried but their element files are not read. Each
PySR stage is segmented and recoverable, so a rerun resumes completed work.

## 1. Imports and package root

In [1]:
from pathlib import Path
import json
import sys

import pandas as pd

try:
    from IPython.display import display
except Exception:
    display = print


def resolve_package_root() -> Path:
    current = Path.cwd().resolve()
    for candidate in [current, *current.parents]:
        if (candidate / "src" / "formal_v11_four_rotation.py").exists():
            return candidate
    raise FileNotFoundError("Could not locate the NotebookCT3 package root.")


PACKAGE_ROOT = resolve_package_root()
if str(PACKAGE_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(PACKAGE_ROOT / "src"))

print("Package root:", PACKAGE_ROOT)
print("Python:", sys.executable)

Package root: /net/scratch/j96317yn/NotebookCT3
Python: /net/scratch/j96317yn/NotebookCT3/.venv/bin/python

## 2. Run or resume the locked rotation

In [2]:
from formal_v11_four_rotation import output_directory, run_formal_rotation

ITERATION = 4
RUN_FORMAL_ROTATION = True
OUTPUT_DIR = output_directory(PACKAGE_ROOT, ITERATION)

if RUN_FORMAL_ROTATION:
    RESULT = run_formal_rotation(PACKAGE_ROOT, ITERATION)
    display(pd.DataFrame([RESULT]))
else:
    RESULT = None
    print("Formal rotation skipped.")

[1/119] V10 signed-residual sample: case_01

[2/119] V10 signed-residual sample: case_06

[3/119] V10 signed-residual sample: case_10

[4/119] V10 signed-residual sample: case_12

[5/119] V10 signed-residual sample: case_13

[6/119] V10 signed-residual sample: case_14

[7/119] V10 signed-residual sample: case_15

[8/119] V10 signed-residual sample: case_16

[9/119] V10 signed-residual sample: case_18

[10/119] V10 signed-residual sample: case_19

[11/119] V10 signed-residual sample: case_20

[12/119] V10 signed-residual sample: case_21

[13/119] V10 signed-residual sample: case_24

[14/119] V10 signed-residual sample: case_27

[15/119] V10 signed-residual sample: case_28

[16/119] V10 signed-residual sample: case_29

[17/119] V10 signed-residual sample: case_32

[18/119] V10 signed-residual sample: case_34

[19/119] V10 signed-residual sample: case_35

[20/119] V10 signed-residual sample: case_36

[21/119] V10 signed-residual sample: case_39

[22/119] V10 signed-residual sample: case_40

[23/119] V10 signed-residual sample: case_42

[24/119] V10 signed-residual sample: case_43

[25/119] V10 signed-residual sample: case_45

[26/119] V10 signed-residual sample: case_47

[27/119] V10 signed-residual sample: case_48

[28/119] V10 signed-residual sample: case_49

[29/119] V10 signed-residual sample: case_51

[30/119] V10 signed-residual sample: case_52

[31/119] V10 signed-residual sample: case_54

[32/119] V10 signed-residual sample: case_56

[33/119] V10 signed-residual sample: case_57

[34/119] V10 signed-residual sample: case_58

[35/119] V10 signed-residual sample: case_59

[36/119] V10 signed-residual sample: case_60

[37/119] V10 signed-residual sample: case_62

[38/119] V10 signed-residual sample: case_63

[39/119] V10 signed-residual sample: case_64

[40/119] V10 signed-residual sample: case_66

[41/119] V10 signed-residual sample: case_67

[42/119] V10 signed-residual sample: case_68

[43/119] V10 signed-residual sample: case_71

[44/119] V10 signed-residual sample: case_72

[45/119] V10 signed-residual sample: case_73

[46/119] V10 signed-residual sample: case_74

[47/119] V10 signed-residual sample: case_75

[48/119] V10 signed-residual sample: case_77

[49/119] V10 signed-residual sample: case_81

[50/119] V10 signed-residual sample: case_82

[51/119] V10 signed-residual sample: case_83

[52/119] V10 signed-residual sample: case_84

[53/119] V10 signed-residual sample: case_85

[54/119] V10 signed-residual sample: case_86

[55/119] V10 signed-residual sample: case_87

[56/119] V10 signed-residual sample: case_92

[57/119] V10 signed-residual sample: case_93

[58/119] V10 signed-residual sample: case_94

[59/119] V10 signed-residual sample: case_95

[60/119] V10 signed-residual sample: case_96

[61/119] V10 signed-residual sample: case_97

[62/119] V10 signed-residual sample: case_98

[63/119] V10 signed-residual sample: case_100

[64/119] V10 signed-residual sample: case_101

[65/119] V10 signed-residual sample: case_102

[66/119] V10 signed-residual sample: case_104

[67/119] V10 signed-residual sample: case_105

[68/119] V10 signed-residual sample: case_106

[69/119] V10 signed-residual sample: case_110

[70/119] V10 signed-residual sample: case_111

[71/119] V10 signed-residual sample: case_114

[72/119] V10 signed-residual sample: case_115

[73/119] V10 signed-residual sample: case_116

[74/119] V10 signed-residual sample: case_117

[75/119] V10 signed-residual sample: case_119

[76/119] V10 signed-residual sample: case_120

[77/119] V10 signed-residual sample: case_121

[78/119] V10 signed-residual sample: case_122

[79/119] V10 signed-residual sample: case_125

[80/119] V10 signed-residual sample: case_127

[81/119] V10 signed-residual sample: case_128

[82/119] V10 signed-residual sample: case_129

[83/119] V10 signed-residual sample: case_130

[84/119] V10 signed-residual sample: case_136

[85/119] V10 signed-residual sample: case_137

[86/119] V10 signed-residual sample: case_141

[87/119] V10 signed-residual sample: case_142

[88/119] V10 signed-residual sample: case_143

[89/119] V10 signed-residual sample: case_144

[90/119] V10 signed-residual sample: case_145

[91/119] V10 signed-residual sample: case_146

[92/119] V10 signed-residual sample: case_147

[93/119] V10 signed-residual sample: case_148

[94/119] V10 signed-residual sample: case_150

[95/119] V10 signed-residual sample: case_151

[96/119] V10 signed-residual sample: case_153

[97/119] V10 signed-residual sample: case_155

[98/119] V10 signed-residual sample: case_157

[99/119] V10 signed-residual sample: case_158

[100/119] V10 signed-residual sample: case_159

[101/119] V10 signed-residual sample: case_164

[102/119] V10 signed-residual sample: case_165

[103/119] V10 signed-residual sample: case_169

[104/119] V10 signed-residual sample: case_170

[105/119] V10 signed-residual sample: case_171

[106/119] V10 signed-residual sample: case_173

[107/119] V10 signed-residual sample: case_175

[108/119] V10 signed-residual sample: case_176

[109/119] V10 signed-residual sample: case_179

[110/119] V10 signed-residual sample: case_181

[111/119] V10 signed-residual sample: case_182

[112/119] V10 signed-residual sample: case_184

[113/119] V10 signed-residual sample: case_187

[114/119] V10 signed-residual sample: case_188

[115/119] V10 signed-residual sample: case_193

[116/119] V10 signed-residual sample: case_194

[117/119] V10 signed-residual sample: case_195

[118/119] V10 signed-residual sample: case_196

[119/119] V10 signed-residual sample: case_197

V10 geometry segment 1/5, attempt 1: fresh search

V10 geometry segment 1, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=False

V10 geometry segment 1, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 1, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 1: complete; planned cumulative 800/4000

V10 geometry segment 2/5, attempt 1: resume

V10 geometry segment 2, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 2, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 2, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 2: complete; planned cumulative 1600/4000

V10 geometry segment 3/5, attempt 1: resume

V10 geometry segment 3, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 3, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 3, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 3: complete; planned cumulative 2400/4000

V10 geometry segment 4/5, attempt 1: resume

V10 geometry segment 4, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 4, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 4, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 4: complete; planned cumulative 3200/4000

V10 geometry segment 5/5, attempt 1: resume

V10 geometry segment 5, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 5, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 5, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 5: complete; planned cumulative 4000/4000

[1/15] validation complete-case V10 geometry: case_11

[2/15] validation complete-case V10 geometry: case_17

[3/15] validation complete-case V10 geometry: case_44

[4/15] validation complete-case V10 geometry: case_61

[5/15] validation complete-case V10 geometry: case_69

[6/15] validation complete-case V10 geometry: case_78

[7/15] validation complete-case V10 geometry: case_91

[8/15] validation complete-case V10 geometry: case_107

[9/15] validation complete-case V10 geometry: case_109

[10/15] validation complete-case V10 geometry: case_139

[11/15] validation complete-case V10 geometry: case_166

[12/15] validation complete-case V10 geometry: case_183

[13/15] validation complete-case V10 geometry: case_191

[14/15] validation complete-case V10 geometry: case_192

[15/15] validation complete-case V10 geometry: case_199

/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False  True  True  True  True  True  True  True  True  True
  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False  True False False False False False False False False
 False False False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False False False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False False False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False  True  True  True  True  True
  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False False False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid

V10 physical segment 1/5, attempt 1: fresh search

V10 physical segment 1, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=False

V10 physical segment 1, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V10 physical segment 1: complete; planned cumulative 800/4000

V10 physical segment 2/5, attempt 1: resume

V10 physical segment 2, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V10 physical segment 2, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V10 physical segment 2, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V10 physical segment 2: complete; planned cumulative 1600/4000

V10 physical segment 3/5, attempt 1: resume

V10 physical segment 3, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V10 physical segment 3, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V10 physical segment 3, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V10 physical segment 3: complete; planned cumulative 2400/4000

V10 physical segment 4/5, attempt 1: resume

V10 physical segment 4, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V10 physical segment 4, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V10 physical segment 4, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V10 physical segment 4: complete; planned cumulative 3200/4000

V10 physical segment 5/5, attempt 1: resume

V10 physical segment 5, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V10 physical segment 5, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V10 physical segment 5, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V10 physical segment 5: complete; planned cumulative 4000/4000

[1/15] validation complete-case V10 physical: case_11

[2/15] validation complete-case V10 physical: case_17

[3/15] validation complete-case V10 physical: case_44

[4/15] validation complete-case V10 physical: case_61

[5/15] validation complete-case V10 physical: case_69

[6/15] validation complete-case V10 physical: case_78

[7/15] validation complete-case V10 physical: case_91

[8/15] validation complete-case V10 physical: case_107

[9/15] validation complete-case V10 physical: case_109

[10/15] validation complete-case V10 physical: case_139

[11/15] validation complete-case V10 physical: case_166

[12/15] validation complete-case V10 physical: case_183

[13/15] validation complete-case V10 physical: case_191

[14/15] validation complete-case V10 physical: case_192

[15/15] validation complete-case V10 physical: case_199

[1/15] internal_test complete-case V10 physical: case_79

/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True False False False False False False  True  True  True  True  True
  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid

[2/15] internal_test complete-case V10 physical: case_89

[3/15] internal_test complete-case V10 physical: case_99

[4/15] internal_test complete-case V10 physical: case_118

[5/15] internal_test complete-case V10 physical: case_124

[6/15] internal_test complete-case V10 physical: case_133

[7/15] internal_test complete-case V10 physical: case_154

[8/15] internal_test complete-case V10 physical: case_156

[9/15] internal_test complete-case V10 physical: case_163

[10/15] internal_test complete-case V10 physical: case_180

[11/15] internal_test complete-case V10 physical: case_185

[12/15] internal_test complete-case V10 physical: case_186

[13/15] internal_test complete-case V10 physical: case_189

[14/15] internal_test complete-case V10 physical: case_190

[15/15] internal_test complete-case V10 physical: case_200

V11 tail segment 1/5, attempt 1: fresh search

V11 segment 1, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=False

V11 segment 1, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V11 segment 1, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V11 tail segment 1: complete; planned cumulative 800/4000

V11 tail segment 2/5, attempt 1: resume

V11 segment 2, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V11 segment 2, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V11 segment 2, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V11 tail segment 2: complete; planned cumulative 1600/4000

V11 tail segment 3/5, attempt 1: resume

V11 segment 3, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V11 segment 3, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V11 segment 3, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V11 tail segment 3: complete; planned cumulative 2400/4000

V11 tail segment 4/5, attempt 1: resume

V11 segment 4, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V11 segment 4, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V11 segment 4, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V11 tail segment 4: complete; planned cumulative 3200/4000

V11 tail segment 5/5, attempt 1: resume

V11 segment 5, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V11 segment 5, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V11 segment 5, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V11 tail segment 5: complete; planned cumulative 4000/4000

[1/15] validation complete-case V11: case_11

[2/15] validation complete-case V11: case_17

[3/15] validation complete-case V11: case_44

[4/15] validation complete-case V11: case_61

[5/15] validation complete-case V11: case_69

[6/15] validation complete-case V11: case_78

[7/15] validation complete-case V11: case_91

[8/15] validation complete-case V11: case_107

[9/15] validation complete-case V11: case_109

[10/15] validation complete-case V11: case_139

[11/15] validation complete-case V11: case_166

[12/15] validation complete-case V11: case_183

[13/15] validation complete-case V11: case_191

[14/15] validation complete-case V11: case_192

[15/15] validation complete-case V11: case_199

[1/15] internal_test complete-case V11: case_79

/net/scratch/j96317yn/NotebookCT3/src/v11_tail_aware_localised_symbolic.py:1173: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v11_tail_aware_localised_symbolic.py:1173: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v11_tail_aware_localised_symbolic.py:1173: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True False False False False False False False False False False False
 False False False False False False False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v11_tail_aware_localised_symbolic.py:1173: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True False False False False False False False False False False False
 False False False False False False False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v11_tail_aware_localised_symbolic.py:1173: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v11_tail_aware_localised_symbolic.py:1173: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False  True
 False  True False False False False  True False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v11_tail_aware_localised_symbolic.py:1173: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False False False False False False False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v11_tail_aware_localised_symbolic.py:1173: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False False False False False False False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v11_tail_aware_localised_symbolic.py:1173: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v11_tail_aware_localised_symbolic.py:1173: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False False False False False False False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid

[2/15] internal_test complete-case V11: case_89

[3/15] internal_test complete-case V11: case_99

[4/15] internal_test complete-case V11: case_118

[5/15] internal_test complete-case V11: case_124

[6/15] internal_test complete-case V11: case_133

[7/15] internal_test complete-case V11: case_154

[8/15] internal_test complete-case V11: case_156

[9/15] internal_test complete-case V11: case_163

[10/15] internal_test complete-case V11: case_180

[11/15] internal_test complete-case V11: case_185

[12/15] internal_test complete-case V11: case_186

[13/15] internal_test complete-case V11: case_189

[14/15] internal_test complete-case V11: case_190

[15/15] internal_test complete-case V11: case_200

[1/15] validation: full-case gain audit for case_11

[2/15] validation: full-case gain audit for case_17

[3/15] validation: full-case gain audit for case_44

[4/15] validation: full-case gain audit for case_61

[5/15] validation: full-case gain audit for case_69

[6/15] validation: full-case gain audit for case_78

[7/15] validation: full-case gain audit for case_91

[8/15] validation: full-case gain audit for case_107

[9/15] validation: full-case gain audit for case_109

[10/15] validation: full-case gain audit for case_139

[11/15] validation: full-case gain audit for case_166

[12/15] validation: full-case gain audit for case_183

[13/15] validation: full-case gain audit for case_191

[14/15] validation: full-case gain audit for case_192

[15/15] validation: full-case gain audit for case_199

[1/15] internal_test: full-case gain audit for case_79

[2/15] internal_test: full-case gain audit for case_89

[3/15] internal_test: full-case gain audit for case_99

[4/15] internal_test: full-case gain audit for case_118

[5/15] internal_test: full-case gain audit for case_124

[6/15] internal_test: full-case gain audit for case_133

[7/15] internal_test: full-case gain audit for case_154

[8/15] internal_test: full-case gain audit for case_156

[9/15] internal_test: full-case gain audit for case_163

[10/15] internal_test: full-case gain audit for case_180

[11/15] internal_test: full-case gain audit for case_185

[12/15] internal_test: full-case gain audit for case_186

[13/15] internal_test: full-case gain audit for case_189

[14/15] internal_test: full-case gain audit for case_190

[15/15] internal_test: full-case gain audit for case_200

,status,iteration,execution_mode,method,selected_gain,v10_population_iterations,v11_population_iterations,train_cases,validation_cases,internal_test_cases,final_test_cases_read,elapsed_seconds,v10_output_directory,v11_output_directory,gain_output_directory
0,complete,4,fresh_rotation_specific_training_and_audit,v10_signed_staged_plus_v11_tail_plus_validatio...,0.85,8000,4000,119,15,15,0,11612.391598,/net/scratch/j96317yn/NotebookCT3/outputs/10_s...,/net/scratch/j96317yn/NotebookCT3/outputs/11_t...,/net/scratch/j96317yn/NotebookCT3/outputs/12_v...

## 3. Saved evidence

In [3]:
roots = {
    "pipeline": OUTPUT_DIR,
    "v10": PACKAGE_ROOT / "outputs/10_signed_staged_residual_symbolic_pilot/iteration_4",
    "v11": PACKAGE_ROOT / "outputs/11_tail_aware_localised_symbolic/iteration_4",
    "gain": PACKAGE_ROOT / "outputs/12_v11_gain_stability_audit/iteration_4",
}

artifacts = {
    "pipeline_completion": roots["pipeline"] / "pipeline_complete.json",
    "v10_completion": roots["v10"] / "pilot_complete.json",
    "v11_completion": roots["v11"] / "pilot_complete.json",
    "gain_completion": roots["gain"] / "audit_complete.json",
    "selected_gain": roots["gain"] / "selected_gain.json",
    "selected_formula": roots["gain"] / "selected_gain_formula.txt",
    "split_metrics": roots["gain"] / "selected_models_split_metrics.csv",
}
for name, artifact in artifacts.items():
    print(f"{name:22s} exists={artifact.exists()}  {artifact}")

if artifacts["split_metrics"].exists():
    display(pd.read_csv(artifacts["split_metrics"]))
if artifacts["selected_formula"].exists():
    print("\n" + artifacts["selected_formula"].read_text(encoding="utf-8"))

pipeline_completion    exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/17_v11_four_rotation_formal/iteration_4/pipeline_complete.json
v10_completion         exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/10_signed_staged_residual_symbolic_pilot/iteration_4/pilot_complete.json
v11_completion         exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/11_tail_aware_localised_symbolic/iteration_4/pilot_complete.json
gain_completion        exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/12_v11_gain_stability_audit/iteration_4/audit_complete.json
selected_gain          exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/12_v11_gain_stability_audit/iteration_4/selected_gain.json
selected_formula       exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/12_v11_gain_stability_audit/iteration_4/selected_gain_formula.txt
split_metrics          exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/12_v11_gain_stability_audit/iteration_4/selected_models_split_metrics.csv

,iteration,split,model,reporting_role,n_cases,n_elements_evaluated,micro_mae,micro_rmse,micro_r2,macro_mae,...,mean_top5_actual_rmse,mean_top5_actual_bias,mean_p95_relative_error,mean_p95_underprediction_fraction,mean_p99_relative_error,mean_p99_underprediction_fraction,mean_top5pct_hotspot_overlap,mean_top1pct_hotspot_overlap,mean_top1_recall_in_predicted_top5,max_prediction_abs_max_ratio
0,4,internal_test,v10_signed_staged_symbolic,parent_reference,15,6005400,1.196517,1.690032,0.589396,1.196517,...,3.439301,-2.209281,0.020883,0.002226,0.168589,0.168589,0.520601,0.499700,0.824592,1.147153
1,4,internal_test,v11_current_gain_1_00,current_v11,15,6005400,1.176512,1.660987,0.603388,1.176512,...,3.819557,-2.774037,0.052678,0.052678,0.212650,0.212650,0.520601,0.499700,0.824592,1.114129
2,4,internal_test,v11_mean_calibrated_v10,mean_calibration_only,15,6005400,1.176512,1.660987,0.603388,1.176512,...,3.819557,-2.774037,0.052678,0.052678,0.212650,0.212650,0.520601,0.499700,0.824592,1.114129
3,4,internal_test,v11_selected_gain_0.85,validation_selected,15,6005400,1.176512,1.660987,0.603388,1.176512,...,3.819557,-2.774037,0.052678,0.052678,0.212650,0.212650,0.520601,0.499700,0.824592,1.114129
4,4,validation,v10_signed_staged_symbolic,parent_reference,15,6005400,1.288084,1.839340,0.605601,1.288084,...,3.817238,-2.550858,0.023958,0.001057,0.184544,0.184544,0.507150,0.501765,0.818498,0.813958
5,4,validation,v11_current_gain_1_00,current_v11,15,6005400,1.283426,1.819404,0.614104,1.283426,...,4.216390,-3.117843,0.052031,0.046899,0.224717,0.224717,0.507150,0.501765,0.818498,0.795099
6,4,validation,v11_mean_calibrated_v10,mean_calibration_only,15,6005400,1.283426,1.819404,0.614104,1.283426,...,4.216390,-3.117843,0.052031,0.046899,0.224717,0.224717,0.507150,0.501765,0.818498,0.795099
7,4,validation,v11_selected_gain_0.85,validation_selected,15,6005400,1.283426,1.819404,0.614104,1.283426,...,4.216390,-3.117843,0.052031,0.046899,0.224717,0.224717,0.507150,0.501765,0.818498,0.795099

CT3 frozen V11 gain-audited stress formula
===========================================

Selected tail gain lambda = 0.85

sigma_v10 = (-0.0116301024532845*temperature_mean + 0.0470427355318997*temperature_p95 - 3.16087946558646*weight_loss_rate_mean + 0.103449215368151*z_max - 0.870195660324862*Abs(4.60760803334225*fluence_rate_p95 - 20.3572633494299) - 100.195330145459) + exp(-1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276) * ((1.10317833861391*(0.55673575*(0.0509611749551904*rho - 9.32241465638866)*(0.0509611749551904*rho - 8.66867535638866) - 31.9731949759449*(theta_cos - 0.922666019258146)**2)*(Abs(0.0509611749551904*rho - 8.59575422638866) - 2.4201684) + 0.285739561816426) + (0.26613534581272986*signed_axial_position_proxy - 0.1622288885733871*(6.35717263336409*nearest_axial_boundary_fraction_proxy - 1.50609073609435)*(-7.0761696316530864*nearest_axial_boundary_fraction_proxy + 7.2459763106469*nearest_radial_boundary_fraction_proxy - 0.069780171113859076*rho - (6.35717263336409*nearest_axial_boundary_fraction_proxy - 1.50609073609435)*(7.2459763106469*nearest_radial_boundary_fraction_proxy - 2.38325249598573) + 12.075351442964397) - 0.1622288885733871*Abs(7.94873136269381*nearest_angular_boundary_fraction_proxy + 7.2459763106469*nearest_radial_boundary_fraction_proxy - 2.21701884243319*signed_angular_position_proxy - 4.509683458131166) + 0.13991710730167015) + (-0.10412130908674733*(7.2459763106469*nearest_radial_boundary_fraction_proxy - 2.38325249598573)*(2.63391439710955*fluence_rate_mean + (43.826976828009*boundary_corner_proximity_proxy - 1.00232009854836)*(2.40096813285283*signed_radial_position_proxy + 0.381717477146586) - 9.50597278012606) + 0.0296437391158275))
delta_mu_case = (1.115051609186759) + (-0.1190607671440357)*fluence_rate_mean + (-0.1198020206288154)*fluence_rate_p95 + (-1.119477958133205e-05)*temperature_mean + (-0.003186256293774443)*temperature_p95 + (0.5740339285340504)*weight_loss_rate_mean + (7.029490394614275)*weight_loss_rate_std
log_scale_v10 = -1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276
tail_raw_v11 = 0.3011451373613095
tail_centered_v11 = tail_raw_v11 - case_mean(tail_raw_v11)

Combined expression
sigma = ((-0.0116301024532845*temperature_mean + 0.0470427355318997*temperature_p95 - 3.16087946558646*weight_loss_rate_mean + 0.103449215368151*z_max - 0.870195660324862*Abs(4.60760803334225*fluence_rate_p95 - 20.3572633494299) - 100.195330145459) + exp(-1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276) * ((1.10317833861391*(0.55673575*(0.0509611749551904*rho - 9.32241465638866)*(0.0509611749551904*rho - 8.66867535638866) - 31.9731949759449*(theta_cos - 0.922666019258146)**2)*(Abs(0.0509611749551904*rho - 8.59575422638866) - 2.4201684) + 0.285739561816426) + (0.26613534581272986*signed_axial_position_proxy - 0.1622288885733871*(6.35717263336409*nearest_axial_boundary_fraction_proxy - 1.50609073609435)*(-7.0761696316530864*nearest_axial_boundary_fraction_proxy + 7.2459763106469*nearest_radial_boundary_fraction_proxy - 0.069780171113859076*rho - (6.35717263336409*nearest_axial_boundary_fraction_proxy - 1.50609073609435)*(7.2459763106469*nearest_radial_boundary_fraction_proxy - 2.38325249598573) + 12.075351442964397) - 0.1622288885733871*Abs(7.94873136269381*nearest_angular_boundary_fraction_proxy + 7.2459763106469*nearest_radial_boundary_fraction_proxy - 2.21701884243319*signed_angular_position_proxy - 4.509683458131166) + 0.13991710730167015) + (-0.10412130908674733*(7.2459763106469*nearest_radial_boundary_fraction_proxy - 2.38325249598573)*(2.63391439710955*fluence_rate_mean + (43.826976828009*boundary_corner_proximity_proxy - 1.00232009854836)*(2.40096813285283*signed_radial_position_proxy + 0.381717477146586) - 9.50597278012606) + 0.0296437391158275))) + ((1.115051609186759) + (-0.1190607671440357)*fluence_rate_mean + (-0.1198020206288154)*fluence_rate_p95 + (-1.119477958133205e-05)*temperature_mean + (-0.003186256293774443)*temperature_p95 + (0.5740339285340504)*weight_loss_rate_mean + (7.029490394614275)*weight_loss_rate_std) + (0.85) * exp(-1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276) * ((0.3011451373613095) - case_mean(0.3011451373613095))

The selected lambda used only the 15 validation cases.
The 15 internal-test cases were read only after lambda was frozen.
The 50 final-test case element files were not read.
Lambda values above 1.00 were diagnostic and were not selectable.

## Interpretation

This is a development-rotation result, not external validation. Formula
coefficients are expected to change because the training cases change. The
primary questions are whether the same hierarchical method remains useful,
whether selected gain and feature families are reasonably stable, and whether
validation improvements survive the one-time internal-test audit.