# Formal V11 Symbolic Regression: Iteration 2

This notebook runs one complete frozen development rotation:

1. V10 signed staged residual symbolic search, using the Iteration-2
   119 training cases and 595,000 stratified discovery rows;
2. V11 case-mean calibration and tail-aware localised symbolic search;
3. validation-only scalar gain selection, followed by one internal-test audit.

Every complete validation and internal-test case is evaluated. The 50 final
test case names are inventoried but their element files are not read. Each
PySR stage is segmented and recoverable, so a rerun resumes completed work.

## 1. Imports and package root

In [1]:
from pathlib import Path
import json
import sys

import pandas as pd

try:
    from IPython.display import display
except Exception:
    display = print


def resolve_package_root() -> Path:
    current = Path.cwd().resolve()
    for candidate in [current, *current.parents]:
        if (candidate / "src" / "formal_v11_four_rotation.py").exists():
            return candidate
    raise FileNotFoundError("Could not locate the NotebookCT3 package root.")


PACKAGE_ROOT = resolve_package_root()
if str(PACKAGE_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(PACKAGE_ROOT / "src"))

print("Package root:", PACKAGE_ROOT)
print("Python:", sys.executable)

Package root: /net/scratch/j96317yn/NotebookCT3
Python: /net/scratch/j96317yn/NotebookCT3/.venv/bin/python

## 2. Run or resume the locked rotation

In [2]:
from formal_v11_four_rotation import output_directory, run_formal_rotation

ITERATION = 2
RUN_FORMAL_ROTATION = True
OUTPUT_DIR = output_directory(PACKAGE_ROOT, ITERATION)

if RUN_FORMAL_ROTATION:
    RESULT = run_formal_rotation(PACKAGE_ROOT, ITERATION)
    display(pd.DataFrame([RESULT]))
else:
    RESULT = None
    print("Formal rotation skipped.")

[1/119] V10 signed-residual sample: case_01

[2/119] V10 signed-residual sample: case_06

[3/119] V10 signed-residual sample: case_10

[4/119] V10 signed-residual sample: case_11

[5/119] V10 signed-residual sample: case_13

[6/119] V10 signed-residual sample: case_14

[7/119] V10 signed-residual sample: case_15

[8/119] V10 signed-residual sample: case_16

[9/119] V10 signed-residual sample: case_17

[10/119] V10 signed-residual sample: case_18

[11/119] V10 signed-residual sample: case_19

[12/119] V10 signed-residual sample: case_21

[13/119] V10 signed-residual sample: case_24

[14/119] V10 signed-residual sample: case_28

[15/119] V10 signed-residual sample: case_29

[16/119] V10 signed-residual sample: case_32

[17/119] V10 signed-residual sample: case_34

[18/119] V10 signed-residual sample: case_35

[19/119] V10 signed-residual sample: case_36

[20/119] V10 signed-residual sample: case_40

[21/119] V10 signed-residual sample: case_44

[22/119] V10 signed-residual sample: case_45

[23/119] V10 signed-residual sample: case_48

[24/119] V10 signed-residual sample: case_49

[25/119] V10 signed-residual sample: case_51

[26/119] V10 signed-residual sample: case_52

[27/119] V10 signed-residual sample: case_54

[28/119] V10 signed-residual sample: case_56

[29/119] V10 signed-residual sample: case_57

[30/119] V10 signed-residual sample: case_58

[31/119] V10 signed-residual sample: case_59

[32/119] V10 signed-residual sample: case_60

[33/119] V10 signed-residual sample: case_61

[34/119] V10 signed-residual sample: case_62

[35/119] V10 signed-residual sample: case_64

[36/119] V10 signed-residual sample: case_66

[37/119] V10 signed-residual sample: case_67

[38/119] V10 signed-residual sample: case_71

[39/119] V10 signed-residual sample: case_72

[40/119] V10 signed-residual sample: case_73

[41/119] V10 signed-residual sample: case_74

[42/119] V10 signed-residual sample: case_75

[43/119] V10 signed-residual sample: case_77

[44/119] V10 signed-residual sample: case_78

[45/119] V10 signed-residual sample: case_79

[46/119] V10 signed-residual sample: case_82

[47/119] V10 signed-residual sample: case_83

[48/119] V10 signed-residual sample: case_85

[49/119] V10 signed-residual sample: case_86

[50/119] V10 signed-residual sample: case_87

[51/119] V10 signed-residual sample: case_89

[52/119] V10 signed-residual sample: case_91

[53/119] V10 signed-residual sample: case_92

[54/119] V10 signed-residual sample: case_93

[55/119] V10 signed-residual sample: case_95

[56/119] V10 signed-residual sample: case_96

[57/119] V10 signed-residual sample: case_97

[58/119] V10 signed-residual sample: case_98

[59/119] V10 signed-residual sample: case_99

[60/119] V10 signed-residual sample: case_101

[61/119] V10 signed-residual sample: case_102

[62/119] V10 signed-residual sample: case_104

[63/119] V10 signed-residual sample: case_106

[64/119] V10 signed-residual sample: case_107

[65/119] V10 signed-residual sample: case_109

[66/119] V10 signed-residual sample: case_110

[67/119] V10 signed-residual sample: case_111

[68/119] V10 signed-residual sample: case_115

[69/119] V10 signed-residual sample: case_116

[70/119] V10 signed-residual sample: case_117

[71/119] V10 signed-residual sample: case_118

[72/119] V10 signed-residual sample: case_119

[73/119] V10 signed-residual sample: case_120

[74/119] V10 signed-residual sample: case_121

[75/119] V10 signed-residual sample: case_122

[76/119] V10 signed-residual sample: case_125

[77/119] V10 signed-residual sample: case_127

[78/119] V10 signed-residual sample: case_128

[79/119] V10 signed-residual sample: case_129

[80/119] V10 signed-residual sample: case_130

[81/119] V10 signed-residual sample: case_136

[82/119] V10 signed-residual sample: case_137

[83/119] V10 signed-residual sample: case_139

[84/119] V10 signed-residual sample: case_141

[85/119] V10 signed-residual sample: case_142

[86/119] V10 signed-residual sample: case_144

[87/119] V10 signed-residual sample: case_145

[88/119] V10 signed-residual sample: case_146

[89/119] V10 signed-residual sample: case_147

[90/119] V10 signed-residual sample: case_148

[91/119] V10 signed-residual sample: case_150

[92/119] V10 signed-residual sample: case_153

[93/119] V10 signed-residual sample: case_154

[94/119] V10 signed-residual sample: case_155

[95/119] V10 signed-residual sample: case_158

[96/119] V10 signed-residual sample: case_159

[97/119] V10 signed-residual sample: case_163

[98/119] V10 signed-residual sample: case_166

[99/119] V10 signed-residual sample: case_169

[100/119] V10 signed-residual sample: case_170

[101/119] V10 signed-residual sample: case_173

[102/119] V10 signed-residual sample: case_175

[103/119] V10 signed-residual sample: case_179

[104/119] V10 signed-residual sample: case_181

[105/119] V10 signed-residual sample: case_182

[106/119] V10 signed-residual sample: case_183

[107/119] V10 signed-residual sample: case_184

[108/119] V10 signed-residual sample: case_185

[109/119] V10 signed-residual sample: case_186

[110/119] V10 signed-residual sample: case_187

[111/119] V10 signed-residual sample: case_188

[112/119] V10 signed-residual sample: case_191

[113/119] V10 signed-residual sample: case_192

[114/119] V10 signed-residual sample: case_193

[115/119] V10 signed-residual sample: case_195

[116/119] V10 signed-residual sample: case_196

[117/119] V10 signed-residual sample: case_197

[118/119] V10 signed-residual sample: case_199

[119/119] V10 signed-residual sample: case_200

V10 geometry segment 1/5, attempt 1: fresh search

V10 geometry segment 1, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=False

V10 geometry segment 1, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 1: complete; planned cumulative 800/4000

V10 geometry segment 2/5, attempt 1: resume

V10 geometry segment 2, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 2, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 2, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 2: complete; planned cumulative 1600/4000

V10 geometry segment 3/5, attempt 1: resume

V10 geometry segment 3, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 3, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 3, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 3: complete; planned cumulative 2400/4000

V10 geometry segment 4/5, attempt 1: resume

V10 geometry segment 4, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 4, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 4, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 4: complete; planned cumulative 3200/4000

V10 geometry segment 5/5, attempt 1: resume

V10 geometry segment 5, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 5, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V10 geometry segment 5: complete; planned cumulative 4000/4000

[1/15] validation complete-case V10 geometry: case_39

[2/15] validation complete-case V10 geometry: case_47

[3/15] validation complete-case V10 geometry: case_63

[4/15] validation complete-case V10 geometry: case_69

[5/15] validation complete-case V10 geometry: case_81

[6/15] validation complete-case V10 geometry: case_105

[7/15] validation complete-case V10 geometry: case_133

[8/15] validation complete-case V10 geometry: case_143

[9/15] validation complete-case V10 geometry: case_151

[10/15] validation complete-case V10 geometry: case_157

[11/15] validation complete-case V10 geometry: case_165

[12/15] validation complete-case V10 geometry: case_171

[13/15] validation complete-case V10 geometry: case_180

[14/15] validation complete-case V10 geometry: case_189

[15/15] validation complete-case V10 geometry: case_194

/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False  True  True  True  True  True  True  True  True  True
  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False False False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False False False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False False False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False  True  True  True
  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False False False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid

V10 physical segment 1/5, attempt 1: fresh search

V10 physical segment 1, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=False

V10 physical segment 1, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V10 physical segment 1: complete; planned cumulative 800/4000

V10 physical segment 2/5, attempt 1: resume

V10 physical segment 2, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V10 physical segment 2, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V10 physical segment 2: complete; planned cumulative 1600/4000

V10 physical segment 3/5, attempt 1: resume

V10 physical segment 3, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V10 physical segment 3, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V10 physical segment 3: complete; planned cumulative 2400/4000

V10 physical segment 4/5, attempt 1: resume

V10 physical segment 4, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V10 physical segment 4, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V10 physical segment 4: complete; planned cumulative 3200/4000

V10 physical segment 5/5, attempt 1: resume

V10 physical segment 5, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V10 physical segment 5, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V10 physical segment 5: complete; planned cumulative 4000/4000

[1/15] validation complete-case V10 physical: case_39

[2/15] validation complete-case V10 physical: case_47

[3/15] validation complete-case V10 physical: case_63

[4/15] validation complete-case V10 physical: case_69

[5/15] validation complete-case V10 physical: case_81

[6/15] validation complete-case V10 physical: case_105

[7/15] validation complete-case V10 physical: case_133

[8/15] validation complete-case V10 physical: case_143

[9/15] validation complete-case V10 physical: case_151

[10/15] validation complete-case V10 physical: case_157

[11/15] validation complete-case V10 physical: case_165

[12/15] validation complete-case V10 physical: case_171

[13/15] validation complete-case V10 physical: case_180

[14/15] validation complete-case V10 physical: case_189

[15/15] validation complete-case V10 physical: case_194

[1/15] internal_test complete-case V10 physical: case_12

/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False  True  True  True  True  True  True  True  True  True  True
  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/signed_staged_residual_symbolic.py:1310: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  candidate_metrics.loc[valid.index, valid.columns] = valid

[2/15] internal_test complete-case V10 physical: case_20

[3/15] internal_test complete-case V10 physical: case_27

[4/15] internal_test complete-case V10 physical: case_42

[5/15] internal_test complete-case V10 physical: case_43

[6/15] internal_test complete-case V10 physical: case_68

[7/15] internal_test complete-case V10 physical: case_84

[8/15] internal_test complete-case V10 physical: case_94

[9/15] internal_test complete-case V10 physical: case_100

[10/15] internal_test complete-case V10 physical: case_114

[11/15] internal_test complete-case V10 physical: case_124

[12/15] internal_test complete-case V10 physical: case_156

[13/15] internal_test complete-case V10 physical: case_164

[14/15] internal_test complete-case V10 physical: case_176

[15/15] internal_test complete-case V10 physical: case_190

V11 tail segment 1/5, attempt 1: fresh search

V11 segment 1, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=False

V11 segment 1, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V11 tail segment 1: complete; planned cumulative 800/4000

V11 tail segment 2/5, attempt 1: resume

V11 segment 2, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V11 segment 2, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V11 segment 2, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V11 tail segment 2: complete; planned cumulative 1600/4000

V11 tail segment 3/5, attempt 1: resume

V11 segment 3, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V11 segment 3, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V11 segment 3, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V11 tail segment 3: complete; planned cumulative 2400/4000

V11 tail segment 4/5, attempt 1: resume

V11 segment 4, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V11 segment 4, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V11 segment 4, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V11 tail segment 4: complete; planned cumulative 3200/4000

V11 tail segment 5/5, attempt 1: resume

V11 segment 5, attempt 1: elapsed=0.0 min, inactive=0.0 min, checkpoint=True

V11 segment 5, attempt 1: elapsed=5.0 min, inactive=0.0 min, checkpoint=True

V11 segment 5, attempt 1: elapsed=10.0 min, inactive=0.0 min, checkpoint=True

V11 tail segment 5: complete; planned cumulative 4000/4000

[1/15] validation complete-case V11: case_39

[2/15] validation complete-case V11: case_47

[3/15] validation complete-case V11: case_63

[4/15] validation complete-case V11: case_69

[5/15] validation complete-case V11: case_81

[6/15] validation complete-case V11: case_105

[7/15] validation complete-case V11: case_133

[8/15] validation complete-case V11: case_143

[9/15] validation complete-case V11: case_151

[10/15] validation complete-case V11: case_157

[11/15] validation complete-case V11: case_165

[12/15] validation complete-case V11: case_171

[13/15] validation complete-case V11: case_180

[14/15] validation complete-case V11: case_189

[15/15] validation complete-case V11: case_194

[1/15] internal_test complete-case V11: case_12

/net/scratch/j96317yn/NotebookCT3/src/v11_tail_aware_localised_symbolic.py:1173: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v11_tail_aware_localised_symbolic.py:1173: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v11_tail_aware_localised_symbolic.py:1173: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True False False False False False False  True  True  True  True  True
  True  True False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v11_tail_aware_localised_symbolic.py:1173: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True False False False False False False False  True  True False  True
  True  True False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v11_tail_aware_localised_symbolic.py:1173: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v11_tail_aware_localised_symbolic.py:1173: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False False  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v11_tail_aware_localised_symbolic.py:1173: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False False False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v11_tail_aware_localised_symbolic.py:1173: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False False False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v11_tail_aware_localised_symbolic.py:1173: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid
/net/scratch/j96317yn/NotebookCT3/src/v11_tail_aware_localised_symbolic.py:1173: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '[False False False False False False False False False False False False
 False False False False]' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  metrics.loc[valid.index, valid.columns] = valid

[2/15] internal_test complete-case V11: case_20

[3/15] internal_test complete-case V11: case_27

[4/15] internal_test complete-case V11: case_42

[5/15] internal_test complete-case V11: case_43

[6/15] internal_test complete-case V11: case_68

[7/15] internal_test complete-case V11: case_84

[8/15] internal_test complete-case V11: case_94

[9/15] internal_test complete-case V11: case_100

[10/15] internal_test complete-case V11: case_114

[11/15] internal_test complete-case V11: case_124

[12/15] internal_test complete-case V11: case_156

[13/15] internal_test complete-case V11: case_164

[14/15] internal_test complete-case V11: case_176

[15/15] internal_test complete-case V11: case_190

[1/15] validation: full-case gain audit for case_39

[2/15] validation: full-case gain audit for case_47

[3/15] validation: full-case gain audit for case_63

[4/15] validation: full-case gain audit for case_69

[5/15] validation: full-case gain audit for case_81

[6/15] validation: full-case gain audit for case_105

[7/15] validation: full-case gain audit for case_133

[8/15] validation: full-case gain audit for case_143

[9/15] validation: full-case gain audit for case_151

[10/15] validation: full-case gain audit for case_157

[11/15] validation: full-case gain audit for case_165

[12/15] validation: full-case gain audit for case_171

[13/15] validation: full-case gain audit for case_180

[14/15] validation: full-case gain audit for case_189

[15/15] validation: full-case gain audit for case_194

[1/15] internal_test: full-case gain audit for case_12

[2/15] internal_test: full-case gain audit for case_20

[3/15] internal_test: full-case gain audit for case_27

[4/15] internal_test: full-case gain audit for case_42

[5/15] internal_test: full-case gain audit for case_43

[6/15] internal_test: full-case gain audit for case_68

[7/15] internal_test: full-case gain audit for case_84

[8/15] internal_test: full-case gain audit for case_94

[9/15] internal_test: full-case gain audit for case_100

[10/15] internal_test: full-case gain audit for case_114

[11/15] internal_test: full-case gain audit for case_124

[12/15] internal_test: full-case gain audit for case_156

[13/15] internal_test: full-case gain audit for case_164

[14/15] internal_test: full-case gain audit for case_176

[15/15] internal_test: full-case gain audit for case_190

,status,iteration,execution_mode,method,selected_gain,v10_population_iterations,v11_population_iterations,train_cases,validation_cases,internal_test_cases,final_test_cases_read,elapsed_seconds,v10_output_directory,v11_output_directory,gain_output_directory
0,complete,2,fresh_rotation_specific_training_and_audit,v10_signed_staged_plus_v11_tail_plus_validatio...,0.75,8000,4000,119,15,15,0,9256.706527,/net/scratch/j96317yn/NotebookCT3/outputs/10_s...,/net/scratch/j96317yn/NotebookCT3/outputs/11_t...,/net/scratch/j96317yn/NotebookCT3/outputs/12_v...

## 3. Saved evidence

In [3]:
roots = {
    "pipeline": OUTPUT_DIR,
    "v10": PACKAGE_ROOT / "outputs/10_signed_staged_residual_symbolic_pilot/iteration_2",
    "v11": PACKAGE_ROOT / "outputs/11_tail_aware_localised_symbolic/iteration_2",
    "gain": PACKAGE_ROOT / "outputs/12_v11_gain_stability_audit/iteration_2",
}

artifacts = {
    "pipeline_completion": roots["pipeline"] / "pipeline_complete.json",
    "v10_completion": roots["v10"] / "pilot_complete.json",
    "v11_completion": roots["v11"] / "pilot_complete.json",
    "gain_completion": roots["gain"] / "audit_complete.json",
    "selected_gain": roots["gain"] / "selected_gain.json",
    "selected_formula": roots["gain"] / "selected_gain_formula.txt",
    "split_metrics": roots["gain"] / "selected_models_split_metrics.csv",
}
for name, artifact in artifacts.items():
    print(f"{name:22s} exists={artifact.exists()}  {artifact}")

if artifacts["split_metrics"].exists():
    display(pd.read_csv(artifacts["split_metrics"]))
if artifacts["selected_formula"].exists():
    print("\n" + artifacts["selected_formula"].read_text(encoding="utf-8"))

pipeline_completion    exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/17_v11_four_rotation_formal/iteration_2/pipeline_complete.json
v10_completion         exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/10_signed_staged_residual_symbolic_pilot/iteration_2/pilot_complete.json
v11_completion         exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/11_tail_aware_localised_symbolic/iteration_2/pilot_complete.json
gain_completion        exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/12_v11_gain_stability_audit/iteration_2/audit_complete.json
selected_gain          exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/12_v11_gain_stability_audit/iteration_2/selected_gain.json
selected_formula       exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/12_v11_gain_stability_audit/iteration_2/selected_gain_formula.txt
split_metrics          exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/12_v11_gain_stability_audit/iteration_2/selected_models_split_metrics.csv

,iteration,split,model,reporting_role,n_cases,n_elements_evaluated,micro_mae,micro_rmse,micro_r2,macro_mae,...,mean_top5_actual_rmse,mean_top5_actual_bias,mean_p95_relative_error,mean_p95_underprediction_fraction,mean_p99_relative_error,mean_p99_underprediction_fraction,mean_top5pct_hotspot_overlap,mean_top1pct_hotspot_overlap,mean_top1_recall_in_predicted_top5,max_prediction_abs_max_ratio
0,2,internal_test,v10_signed_staged_symbolic,parent_reference,15,6005400,1.334445,1.932331,0.523716,1.334445,...,3.632234,-2.384133,0.041548,0.006905,0.172340,0.172340,0.461478,0.497369,0.821479,1.166581
1,2,internal_test,v11_current_gain_1_00,current_v11,15,6005400,1.381524,1.902033,0.538535,1.381524,...,3.450985,-2.150268,0.053509,0.000238,0.139539,0.138931,0.474033,0.459491,0.859374,1.184632
2,2,internal_test,v11_mean_calibrated_v10,mean_calibration_only,15,6005400,1.286480,1.842745,0.566855,1.286480,...,4.051284,-3.009489,0.052684,0.048648,0.218431,0.218431,0.461478,0.497369,0.821479,1.130459
3,2,internal_test,v11_selected_gain_0.75,validation_selected,15,6005400,1.336649,1.846779,0.564956,1.336649,...,3.545851,-2.365073,0.032565,0.008966,0.167131,0.167131,0.490492,0.486330,0.878205,1.166356
4,2,validation,v10_signed_staged_symbolic,parent_reference,15,6005400,1.259377,1.792433,0.552070,1.259377,...,3.522691,-2.406851,0.029886,0.008149,0.199637,0.199637,0.472012,0.488062,0.840193,0.913849
5,2,validation,v11_current_gain_1_00,current_v11,15,6005400,1.295669,1.763770,0.566281,1.295669,...,3.376426,-2.203138,0.042927,0.001982,0.166567,0.166567,0.478643,0.445155,0.856527,0.944634
6,2,validation,v11_mean_calibrated_v10,mean_calibration_only,15,6005400,1.214158,1.717337,0.588817,1.214158,...,3.922993,-2.966225,0.056115,0.055875,0.243015,0.243015,0.472012,0.488062,0.840193,0.890690
7,2,validation,v11_selected_gain_0.75,validation_selected,15,6005400,1.256910,1.717019,0.588969,1.256910,...,3.468363,-2.393910,0.026214,0.012075,0.193987,0.193987,0.497546,0.474542,0.883100,0.929267

CT3 frozen V11 gain-audited stress formula
===========================================

Selected tail gain lambda = 0.75

sigma_v10 = (-0.0116301024532845*temperature_mean + 0.0470427355318997*temperature_p95 - 3.16087946558646*weight_loss_rate_mean + 0.103449215368151*z_max - 0.870195660324862*Abs(4.60760803334225*fluence_rate_p95 - 20.3572633494299) - 100.195330145459) + exp(-1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276) * ((1.10317833861391*(0.55673575*(0.0509611749551904*rho - 9.32241465638866)*(0.0509611749551904*rho - 8.66867535638866) - 31.9731949759449*(theta_cos - 0.922666019258146)**2)*(Abs(0.0509611749551904*rho - 8.59575422638866) - 2.4201684) + 0.285739561816426) + (0.013448561903935085*rho + 0.47728387820325316*z_fraction_proxy - 0.14564637922329544*(4.12918244017469*radial_axial_signed_interaction_proxy - 0.0672749794120767)**2 - 0.25957527828470824*(3.27700476145386*z_fraction_proxy - 1.74794266617586)**2*(43.6667583874302*boundary_corner_proximity_proxy + 2.41221284098931*signed_radial_position_proxy - 1.33262514125946) - 2.5544146883819192) + (-0.30554813835799807*(-3.21657514159445*nearest_axial_boundary_fraction_proxy + 7.28302970000392*nearest_radial_boundary_fraction_proxy + 0.74873754155936657*(15.6006536140747*theta_cos - 14.4099430342809)**2 - 1.64538465194802)*exp(-(7.28302970000392*nearest_radial_boundary_fraction_proxy - 1.692628259533093)**2) + 0.0182360501390777))
delta_mu_case = (0.6256354042446731) + (-0.04765186178325091)*fluence_rate_mean + (-0.1023858002381455)*fluence_rate_p95 + (0.0007959792058960673)*temperature_mean + (-0.003345656321833511)*temperature_p95 + (0.484802928209425)*weight_loss_rate_mean + (6.288299772036227)*weight_loss_rate_std
log_scale_v10 = -1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276
tail_raw_v11 = -0.7395130863147979*nearest_angular_boundary_fraction_proxy - 0.5659502749777386*tanh(0.5353280385268686 - 0.1308541133824969/(3.416326193660334 - 7.38936236032781*nearest_radial_boundary_fraction_proxy)) + 0.7048825072967699
tail_centered_v11 = tail_raw_v11 - case_mean(tail_raw_v11)

Combined expression
sigma = ((-0.0116301024532845*temperature_mean + 0.0470427355318997*temperature_p95 - 3.16087946558646*weight_loss_rate_mean + 0.103449215368151*z_max - 0.870195660324862*Abs(4.60760803334225*fluence_rate_p95 - 20.3572633494299) - 100.195330145459) + exp(-1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276) * ((1.10317833861391*(0.55673575*(0.0509611749551904*rho - 9.32241465638866)*(0.0509611749551904*rho - 8.66867535638866) - 31.9731949759449*(theta_cos - 0.922666019258146)**2)*(Abs(0.0509611749551904*rho - 8.59575422638866) - 2.4201684) + 0.285739561816426) + (0.013448561903935085*rho + 0.47728387820325316*z_fraction_proxy - 0.14564637922329544*(4.12918244017469*radial_axial_signed_interaction_proxy - 0.0672749794120767)**2 - 0.25957527828470824*(3.27700476145386*z_fraction_proxy - 1.74794266617586)**2*(43.6667583874302*boundary_corner_proximity_proxy + 2.41221284098931*signed_radial_position_proxy - 1.33262514125946) - 2.5544146883819192) + (-0.30554813835799807*(-3.21657514159445*nearest_axial_boundary_fraction_proxy + 7.28302970000392*nearest_radial_boundary_fraction_proxy + 0.74873754155936657*(15.6006536140747*theta_cos - 14.4099430342809)**2 - 1.64538465194802)*exp(-(7.28302970000392*nearest_radial_boundary_fraction_proxy - 1.692628259533093)**2) + 0.0182360501390777))) + ((0.6256354042446731) + (-0.04765186178325091)*fluence_rate_mean + (-0.1023858002381455)*fluence_rate_p95 + (0.0007959792058960673)*temperature_mean + (-0.003345656321833511)*temperature_p95 + (0.484802928209425)*weight_loss_rate_mean + (6.288299772036227)*weight_loss_rate_std) + (0.75) * exp(-1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276) * ((-0.7395130863147979*nearest_angular_boundary_fraction_proxy - 0.5659502749777386*tanh(0.5353280385268686 - 0.1308541133824969/(3.416326193660334 - 7.38936236032781*nearest_radial_boundary_fraction_proxy)) + 0.7048825072967699) - case_mean(-0.7395130863147979*nearest_angular_boundary_fraction_proxy - 0.5659502749777386*tanh(0.5353280385268686 - 0.1308541133824969/(3.416326193660334 - 7.38936236032781*nearest_radial_boundary_fraction_proxy)) + 0.7048825072967699))

The selected lambda used only the 15 validation cases.
The 15 internal-test cases were read only after lambda was frozen.
The 50 final-test case element files were not read.
Lambda values above 1.00 were diagnostic and were not selectable.

## Interpretation

This is a development-rotation result, not external validation. Formula
coefficients are expected to change because the training cases change. The
primary questions are whether the same hierarchical method remains useful,
whether selected gain and feature families are reasonably stable, and whether
validation improvements survive the one-time internal-test audit.