# Frozen V13 Residual-Gain Audit: Iteration 1

V13 improved P99 underprediction and hotspot localisation but worsened RMSE
and P95 error on every development case at full gain. This supplement does
not run a new symbolic search. It freezes the V13 residual expression and
evaluates

\[
\sigma(\lambda)=\sigma_{V11}+\lambda s_{case}(r_{V13}-\bar r_{V13,case}).
\]

The gain grid is selected on all elements of the 15 validation cases. The
selected primary and optional research gains are then frozen and checked on
the internal-development split and all 149 development cases. The 50 final
case element files remain sealed.

## 1. Imports and package root

In [1]:
from pathlib import Path
import json
import sys

import pandas as pd

try:
    from IPython.display import display
except Exception:
    display = print


def resolve_package_root() -> Path:
    current = Path.cwd().resolve()
    for candidate in [current, *current.parents]:
        if (candidate / "src" / "v13_residual_gain_audit.py").exists():
            return candidate
    raise FileNotFoundError("Could not locate the NotebookCT3 package root")


PACKAGE_ROOT = resolve_package_root()
if str(PACKAGE_ROOT / "src") not in sys.path:
    sys.path.insert(0, str(PACKAGE_ROOT / "src"))

from v13_residual_gain_audit import (
    V13ResidualGainAuditConfig,
    output_directory,
    preflight_v13_residual_gain_audit,
    run_v13_residual_gain_audit,
)

print("Package root:", PACKAGE_ROOT)
print("Python:", sys.executable)

Package root: /net/scratch/j96317yn/NotebookCT3
Python: /net/scratch/j96317yn/NotebookCT3/.venv/bin/python

## 2. Locked audit configuration

In [2]:
RUN_GAIN_AUDIT = True
CONFIG = V13ResidualGainAuditConfig()
OUTPUT_DIR = output_directory(PACKAGE_ROOT, CONFIG)

display(pd.DataFrame([CONFIG.__dict__]).T.rename(columns={0: "value"}))
print("Validation gain grid:", CONFIG.gain_grid.tolist())
print("Output directory:", OUTPUT_DIR)

                                                                                                value
iteration                                                                                           1
output_subdir                                                                             iteration_1
gain_values                                         (0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.075, 0.1...
primary_minimum_rmse_improvement_fraction                                                       0.005
primary_maximum_p95_degradation_absolute                                                        0.005
research_maximum_rmse_degradation_fraction                                                       0.01
research_maximum_p95_degradation_absolute                                                        0.01
research_minimum_p99_underprediction_improvemen...                                              0.005
maximum_p99_relative_error                                                                       0.15
maximum_p99_underprediction                                                                       0.1
maximum_top1_overlap_degradation_absolute                                                       0.002
minimum_top1_recall                                                                               0.8
random_seed                                                                                        42

Validation gain grid: [0.0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.075, 0.1, 0.125, 0.15, 0.175, 0.2, 0.25, 0.3, 0.35, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
Output directory: /net/scratch/j96317yn/NotebookCT3/outputs/16_v13_residual_gain_audit/iteration_1

## 3. Frozen-input preflight

This hashes the exact V13 candidate and verifies the parent V13 decision,
candidate index, 149-case development scope and untouched 50-case final seal.

In [3]:
PREFLIGHT = preflight_v13_residual_gain_audit(PACKAGE_ROOT, CONFIG)
display(PREFLIGHT["checks"])
print("Frozen artifacts hashed:", len(PREFLIGHT["hash_audit"]))
print("Frozen V13 candidate:", int(PREFLIGHT["selected"]["candidate_index"]))
print("Final-test cases inventoried, not read:", len(PREFLIGHT["inputs"]["final_ids"]))

                     check     value  expected  pass
0              train_cases       119       119  True
1         validation_cases        15        15  True
2           internal_cases        15        15  True
3        development_cases       149       149  True
4       sealed_final_cases        50        50  True
5      parent_v13_complete  complete  complete  True
6  parent_final_cases_read         0         0  True
7           gain_grid_size        22        22  True
8          candidate_index         2         2  True

Frozen artifacts hashed: 7
Frozen V13 candidate: 2
Final-test cases inventoried, not read: 50

## 4. Run the complete-case gain audit

The validation grid is evaluated first. Only after the gains are frozen are
the train and internal-development cases evaluated. Per-case CSV caches allow
the audit to resume after interruption without re-reading completed cases.

In [4]:
RESULT = None
if RUN_GAIN_AUDIT:
    RESULT = run_v13_residual_gain_audit(PACKAGE_ROOT, CONFIG)
    display(pd.DataFrame([RESULT]))
else:
    print("Gain audit skipped because RUN_GAIN_AUDIT=False")

[1/15] validation: V13 residual gain audit for case_18

[2/15] validation: V13 residual gain audit for case_29

[3/15] validation: V13 residual gain audit for case_45

[4/15] validation: V13 residual gain audit for case_51

[5/15] validation: V13 residual gain audit for case_54

[6/15] validation: V13 residual gain audit for case_60

[7/15] validation: V13 residual gain audit for case_62

[8/15] validation: V13 residual gain audit for case_81

[9/15] validation: V13 residual gain audit for case_83

[10/15] validation: V13 residual gain audit for case_86

[11/15] validation: V13 residual gain audit for case_87

[12/15] validation: V13 residual gain audit for case_101

[13/15] validation: V13 residual gain audit for case_120

[14/15] validation: V13 residual gain audit for case_145

[15/15] validation: V13 residual gain audit for case_176

[1/119] train: V13 residual gain audit for case_01

[2/119] train: V13 residual gain audit for case_10

[3/119] train: V13 residual gain audit for case_11

[4/119] train: V13 residual gain audit for case_12

[5/119] train: V13 residual gain audit for case_13

[6/119] train: V13 residual gain audit for case_14

[7/119] train: V13 residual gain audit for case_15

[8/119] train: V13 residual gain audit for case_16

[9/119] train: V13 residual gain audit for case_17

[10/119] train: V13 residual gain audit for case_19

[11/119] train: V13 residual gain audit for case_20

[12/119] train: V13 residual gain audit for case_21

[13/119] train: V13 residual gain audit for case_24

[14/119] train: V13 residual gain audit for case_27

[15/119] train: V13 residual gain audit for case_32

[16/119] train: V13 residual gain audit for case_34

[17/119] train: V13 residual gain audit for case_35

[18/119] train: V13 residual gain audit for case_36

[19/119] train: V13 residual gain audit for case_39

[20/119] train: V13 residual gain audit for case_40

[21/119] train: V13 residual gain audit for case_42

[22/119] train: V13 residual gain audit for case_43

[23/119] train: V13 residual gain audit for case_44

[24/119] train: V13 residual gain audit for case_47

[25/119] train: V13 residual gain audit for case_48

[26/119] train: V13 residual gain audit for case_49

[27/119] train: V13 residual gain audit for case_52

[28/119] train: V13 residual gain audit for case_56

[29/119] train: V13 residual gain audit for case_58

[30/119] train: V13 residual gain audit for case_59

[31/119] train: V13 residual gain audit for case_61

[32/119] train: V13 residual gain audit for case_63

[33/119] train: V13 residual gain audit for case_64

[34/119] train: V13 residual gain audit for case_67

[35/119] train: V13 residual gain audit for case_68

[36/119] train: V13 residual gain audit for case_69

[37/119] train: V13 residual gain audit for case_72

[38/119] train: V13 residual gain audit for case_73

[39/119] train: V13 residual gain audit for case_74

[40/119] train: V13 residual gain audit for case_75

[41/119] train: V13 residual gain audit for case_77

[42/119] train: V13 residual gain audit for case_78

[43/119] train: V13 residual gain audit for case_79

[44/119] train: V13 residual gain audit for case_84

[45/119] train: V13 residual gain audit for case_85

[46/119] train: V13 residual gain audit for case_89

[47/119] train: V13 residual gain audit for case_91

[48/119] train: V13 residual gain audit for case_92

[49/119] train: V13 residual gain audit for case_94

[50/119] train: V13 residual gain audit for case_95

[51/119] train: V13 residual gain audit for case_96

[52/119] train: V13 residual gain audit for case_97

[53/119] train: V13 residual gain audit for case_99

[54/119] train: V13 residual gain audit for case_100

[55/119] train: V13 residual gain audit for case_104

[56/119] train: V13 residual gain audit for case_105

[57/119] train: V13 residual gain audit for case_106

[58/119] train: V13 residual gain audit for case_107

[59/119] train: V13 residual gain audit for case_109

[60/119] train: V13 residual gain audit for case_110

[61/119] train: V13 residual gain audit for case_111

[62/119] train: V13 residual gain audit for case_114

[63/119] train: V13 residual gain audit for case_115

[64/119] train: V13 residual gain audit for case_116

[65/119] train: V13 residual gain audit for case_118

[66/119] train: V13 residual gain audit for case_119

[67/119] train: V13 residual gain audit for case_121

[68/119] train: V13 residual gain audit for case_122

[69/119] train: V13 residual gain audit for case_124

[70/119] train: V13 residual gain audit for case_125

[71/119] train: V13 residual gain audit for case_127

[72/119] train: V13 residual gain audit for case_128

[73/119] train: V13 residual gain audit for case_129

[74/119] train: V13 residual gain audit for case_130

[75/119] train: V13 residual gain audit for case_133

[76/119] train: V13 residual gain audit for case_136

[77/119] train: V13 residual gain audit for case_137

[78/119] train: V13 residual gain audit for case_139

[79/119] train: V13 residual gain audit for case_141

[80/119] train: V13 residual gain audit for case_142

[81/119] train: V13 residual gain audit for case_143

[82/119] train: V13 residual gain audit for case_144

[83/119] train: V13 residual gain audit for case_146

[84/119] train: V13 residual gain audit for case_148

[85/119] train: V13 residual gain audit for case_150

[86/119] train: V13 residual gain audit for case_151

[87/119] train: V13 residual gain audit for case_153

[88/119] train: V13 residual gain audit for case_154

[89/119] train: V13 residual gain audit for case_155

[90/119] train: V13 residual gain audit for case_156

[91/119] train: V13 residual gain audit for case_157

[92/119] train: V13 residual gain audit for case_158

[93/119] train: V13 residual gain audit for case_163

[94/119] train: V13 residual gain audit for case_164

[95/119] train: V13 residual gain audit for case_165

[96/119] train: V13 residual gain audit for case_166

[97/119] train: V13 residual gain audit for case_169

[98/119] train: V13 residual gain audit for case_170

[99/119] train: V13 residual gain audit for case_171

[100/119] train: V13 residual gain audit for case_173

[101/119] train: V13 residual gain audit for case_175

[102/119] train: V13 residual gain audit for case_179

[103/119] train: V13 residual gain audit for case_180

[104/119] train: V13 residual gain audit for case_181

[105/119] train: V13 residual gain audit for case_182

[106/119] train: V13 residual gain audit for case_183

[107/119] train: V13 residual gain audit for case_184

[108/119] train: V13 residual gain audit for case_185

[109/119] train: V13 residual gain audit for case_186

[110/119] train: V13 residual gain audit for case_187

[111/119] train: V13 residual gain audit for case_188

[112/119] train: V13 residual gain audit for case_189

[113/119] train: V13 residual gain audit for case_190

[114/119] train: V13 residual gain audit for case_191

[115/119] train: V13 residual gain audit for case_192

[116/119] train: V13 residual gain audit for case_193

[117/119] train: V13 residual gain audit for case_194

[118/119] train: V13 residual gain audit for case_195

[119/119] train: V13 residual gain audit for case_200

[1/15] internal_test: V13 residual gain audit for case_06

[2/15] internal_test: V13 residual gain audit for case_28

[3/15] internal_test: V13 residual gain audit for case_57

[4/15] internal_test: V13 residual gain audit for case_66

[5/15] internal_test: V13 residual gain audit for case_71

[6/15] internal_test: V13 residual gain audit for case_82

[7/15] internal_test: V13 residual gain audit for case_93

[8/15] internal_test: V13 residual gain audit for case_98

[9/15] internal_test: V13 residual gain audit for case_102

[10/15] internal_test: V13 residual gain audit for case_117

[11/15] internal_test: V13 residual gain audit for case_147

[12/15] internal_test: V13 residual gain audit for case_159

[13/15] internal_test: V13 residual gain audit for case_196

[14/15] internal_test: V13 residual gain audit for case_197

[15/15] internal_test: V13 residual gain audit for case_199

,status,iteration,parent_candidate_index,validation_gain_count,validation_cases,internal_cases,train_cases,development_cases_evaluated,primary_model_decision,research_correction_decision,primary_gain,research_gain,proceed_to_iterations_2_4,final_test_cases_read,elapsed_seconds,output_directory
0,complete,1,2,22,15,15,119,149,freeze_v11_global_gain_0_90_as_primary_model,retain_v13_as_non_deployed_tail_correction_res...,0.0,0.125,True,0,270.449886,/net/scratch/j96317yn/NotebookCT3/outputs/16_v...

## 5. Saved decision evidence

In [5]:
artifacts = {
    "completion": OUTPUT_DIR / "gain_audit_complete.json",
    "decision": OUTPUT_DIR / "residual_gain_decision.json",
    "validation_selection": OUTPUT_DIR / "validation_gain_selection.json",
    "analytic_gain": OUTPUT_DIR / "validation_analytic_gain_summary.json",
    "validation_grid": OUTPUT_DIR / "validation_gain_grid_metrics.csv",
    "scope_metrics": OUTPUT_DIR / "selected_gain_scope_metrics.csv",
    "gates": OUTPUT_DIR / "gain_confirmation_gates.csv",
    "formula": OUTPUT_DIR / "selected_gain_formula.txt",
}
for name, path in artifacts.items():
    print(f"{name:22s} exists={path.exists()}  {path}")

if artifacts["decision"].exists():
    print(json.dumps(json.loads(artifacts["decision"].read_text()), indent=2))
if artifacts["analytic_gain"].exists():
    print(json.dumps(json.loads(artifacts["analytic_gain"].read_text()), indent=2))
if artifacts["scope_metrics"].exists():
    display(pd.read_csv(artifacts["scope_metrics"]))
if artifacts["gates"].exists():
    display(pd.read_csv(artifacts["gates"]))
if artifacts["formula"].exists():
    print("\n" + artifacts["formula"].read_text(encoding="utf-8"))

completion             exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/16_v13_residual_gain_audit/iteration_1/gain_audit_complete.json
decision               exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/16_v13_residual_gain_audit/iteration_1/residual_gain_decision.json
validation_selection   exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/16_v13_residual_gain_audit/iteration_1/validation_gain_selection.json
analytic_gain          exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/16_v13_residual_gain_audit/iteration_1/validation_analytic_gain_summary.json
validation_grid        exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/16_v13_residual_gain_audit/iteration_1/validation_gain_grid_metrics.csv
scope_metrics          exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/16_v13_residual_gain_audit/iteration_1/selected_gain_scope_metrics.csv
gates                  exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/16_v13_residual_gain_audit/iteration_1/gain_confirmation_gates.csv
formula                exists=True  /net/scratch/j96317yn/NotebookCT3/outputs/16_v13_residual_gain_audit/iteration_1/selected_gain_formula.txt
{
  "primary_model_decision": "freeze_v11_global_gain_0_90_as_primary_model",
  "primary_gain": 0.0,
  "primary_gain_confirmed": false,
  "research_correction_decision": "retain_v13_as_non_deployed_tail_correction_research",
  "research_gain": 0.125,
  "research_gain_confirmed": false,
  "proceed_to_iterations_2_4": true,
  "iterations_2_4_role": "V11_method_and_formula_structure_stability_only",
  "final_test_cases_read": 0
}
{
  "validation_micro_sse_optimal_gain_unconstrained": -0.1858315207061089,
  "validation_micro_sse_optimal_gain_clipped_0_1": 0.0,
  "validation_cases_with_positive_optimal_gain": 0,
  "validation_cases_with_nonpositive_optimal_gain": 15,
  "validation_median_unconstrained_gain": -0.17192041765858956
}

,iteration,split,model,gain,n_cases,n_elements_evaluated,micro_mae,micro_rmse,micro_r2,macro_mae,...,mean_top5_actual_rmse,mean_top5_actual_bias,mean_p95_relative_error,mean_p95_underprediction_fraction,mean_p99_relative_error,mean_p99_underprediction_fraction,mean_top5pct_hotspot_overlap,mean_top1pct_hotspot_overlap,mean_top1_recall_in_predicted_top5,max_prediction_abs_max_ratio
0,1,internal_test,v11_global_gain_0_90,0.000,15,6005400,1.312537,1.844602,0.600115,1.312537,...,3.296655,-1.599205,0.040414,0.000485,0.124700,0.118171,0.588347,0.576757,0.882018,1.584976
1,1,internal_test,v13_full_residual_gain_1_00,1.000,15,6005400,1.625743,2.204495,0.428853,1.625743,...,2.842087,-0.619778,0.145058,0.000000,0.056730,0.024678,0.598328,0.600616,0.917699,1.368839
2,1,internal_test,v13_research_residual_gain_0.125,0.125,15,6005400,1.334524,1.865531,0.590989,1.334524,...,3.202403,-1.476777,0.051865,0.000000,0.114253,0.105762,0.594345,0.579770,0.892507,1.536696
3,1,train,v11_global_gain_0_90,0.000,119,47642840,1.196211,1.703422,0.629085,1.196211,...,3.099323,-1.693312,0.038829,0.003359,0.135189,0.132781,0.578520,0.588004,0.880777,1.543172
4,1,train,v13_full_residual_gain_1_00,1.000,119,47642840,1.459595,2.002589,0.487358,1.459595,...,2.634458,-0.829380,0.130637,0.000000,0.058898,0.037383,0.589641,0.614457,0.915412,1.341104
5,1,train,v13_research_residual_gain_0.125,0.125,119,47642840,1.213283,1.719455,0.622070,1.213283,...,3.009618,-1.585321,0.046088,0.001292,0.122925,0.119715,0.584746,0.592307,0.888918,1.495879
6,1,validation,v11_global_gain_0_90,0.000,15,6005400,1.228952,1.769763,0.652403,1.228952,...,2.990331,-1.396082,0.077506,0.001988,0.102731,0.088884,0.571915,0.600516,0.881652,1.131529
7,1,validation,v13_full_residual_gain_1_00,1.000,15,6005400,1.508959,2.074353,0.522459,1.508959,...,2.582085,-0.472103,0.175372,0.000000,0.074360,0.011731,0.582096,0.628571,0.916417,0.994618
8,1,validation,v13_research_residual_gain_0.125,0.125,15,6005400,1.246113,1.784673,0.646522,1.246113,...,2.901170,-1.280585,0.086740,0.000737,0.094163,0.077124,0.577640,0.604146,0.889943,1.099486
9,1,all_149_development,v11_global_gain_0_90,0.000,149,59653640,1.211217,1.724897,0.629014,1.211217,...,3.108216,-1.653916,0.042882,0.002932,0.130866,0.126891,0.578844,0.588132,0.880990,1.584976
10,1,all_149_development,v13_full_residual_gain_1_00,1.000,149,59653640,1.481291,2.031091,0.485612,1.481291,...,2.650088,-0.772312,0.136592,0.000000,0.060236,0.033521,0.589756,0.614485,0.915744,1.368839
11,1,all_149_development,v13_research_residual_gain_0.125,0.125,149,59653640,1.228794,1.741336,0.621908,1.228794,...,3.018108,-1.543715,0.050762,0.001106,0.119157,0.114023,0.584997,0.592237,0.889382,1.536696

,decision_layer,gate,pass,observed,criterion
0,primary,positive_primary_gain_selected_on_validation,False,0.000000,> 0
1,research,internal_test_rmse_cost,True,0.010077,0.015
2,research,internal_test_p95_cost,True,0.051865,0.0554137914205892
3,research,internal_test_p99_benefit,True,0.012409,0.005
4,research,internal_test_p99_absolute,False,0.105762,0.1
5,research,internal_test_top1_overlap,True,0.579770,0.5747565767565768
6,research,all_149_development_rmse_cost,True,0.008413,0.01
7,research,all_149_development_p95_cost,True,0.050762,0.052882256964050786
8,research,all_149_development_p99_benefit,True,0.012868,0.005
9,research,all_149_development_p99_absolute,False,0.114023,0.1
10,research,all_149_development_top1_overlap,True,0.592237,0.5861316669907274

V13 frozen residual-gain audit
================================

Primary decision: freeze_v11_global_gain_0_90_as_primary_model
Research decision: retain_v13_as_non_deployed_tail_correction_research

Primary stress model:
sigma_primary = sigma_V11

Frozen V13 raw residual:
r_raw = 0.0676190077581068*(7.37326359099678*nearest_angular_boundary_fraction_proxy - 0.49547272973709823)*(7.37326359099678*nearest_angular_boundary_fraction_proxy - 7.83718161516892*nearest_radial_boundary_fraction_proxy - 2.342693291125991)*(-0.634665432315235*v11_prediction_within_case_z_proxy + (1.96281136060823*signed_angular_position_proxy + 0.0372013836365022)*(3.62252040885947*theta_sin_4_proxy - 2.63083165891777 + 0.34062078141613944) + 0.980150057039591) + 0.477850708772957
r_centered = r_raw - case_mean(r_raw)

Optional research correction:
lambda_research = 0.125
sigma_research = sigma_V11 + lambda_research * scale_case * r_centered

The optional correction is not the primary stress surrogate unless all primary gates pass.
The 50 final-test case element files were not read.

Frozen parent formula record:
V13 did not pass every predeclared development gate.
The frozen V11 global-gain-0.90 formula remains selected.

sigma_selected = ((-0.0116301024532845*temperature_mean + 0.0470427355318997*temperature_p95 - 3.16087946558646*weight_loss_rate_mean + 0.103449215368151*z_max - 0.870195660324862*Abs(4.60760803334225*fluence_rate_p95 - 20.3572633494299) - 100.195330145459) + exp(-1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276) * ((1.10317833861391*(0.55673575*(0.0509611749551904*rho - 9.32241465638866)*(0.0509611749551904*rho - 8.66867535638866) - 31.9731949759449*(theta_cos - 0.922666019258146)**2)*(Abs(0.0509611749551904*rho - 8.59575422638866) - 2.4201684) + 0.285739561816426) + (0.0005298607274781943*z + 0.17657582192765694*(6.3559467282562*nearest_axial_boundary_fraction_proxy - 1.50570424883607)*(-7.28799975835273*nearest_radial_boundary_fraction_proxy + 0.0517386902634747*rho - 6.047025771972898) - 0.24332347927944745 + 0.793705512144892*exp(-9.5925971595468041*(6.3559467282562*nearest_axial_boundary_fraction_proxy - 0.043846887113135693)**2)) + (0.687707530043104*(3.752650699651312*nearest_angular_boundary_fraction_proxy + 7.28799975835273*nearest_radial_boundary_fraction_proxy - 3.560078810528026 + 0.2777422381074965)*(-0.44608657163711589*fluence_rate_mean - 1.291571739959816*nearest_angular_boundary_fraction_proxy + 0.66354475675260838*theta_fraction_proxy + 0.14984744098602391*Abs(-7.28799975835273*nearest_radial_boundary_fraction_proxy + 2.40848321928096*signed_radial_position_proxy + 2.08439162588874) - 0.07467188916362873 + 1.6933224087437673) + 0.0275995197448158))) + ((-1.052449007433797) + (0.1552525042004941)*fluence_rate_mean + (0.07199435596858993)*fluence_rate_p95 + (0.0001133709738926737)*temperature_mean + (-0.001931509820148126)*temperature_p95 + (0.3846993631715923)*weight_loss_rate_mean + (6.817702583133652)*weight_loss_rate_std) + (0.9) * exp(-1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276) * ((1.2093601333202474*(-0.16122678679851166 + exp(-92.749309109240237*(0.3382200152451777 - 2.08887119255503*signed_angular_position_proxy)**2))*(7.68957066477673*nearest_angular_boundary_fraction_proxy - 2.27807624632193)*(7.38407920683658*nearest_radial_boundary_fraction_proxy + Abs(7.38407920683658*nearest_radial_boundary_fraction_proxy - 2.57458268534255) - 2.57458268534255) + 0.19743823997123105) - case_mean(1.2093601333202474*(-0.16122678679851166 + exp(-92.749309109240237*(0.3382200152451777 - 2.08887119255503*signed_angular_position_proxy)**2))*(7.68957066477673*nearest_angular_boundary_fraction_proxy - 2.27807624632193)*(7.38407920683658*nearest_radial_boundary_fraction_proxy + Abs(7.38407920683658*nearest_radial_boundary_fraction_proxy - 2.57458268534255) - 2.57458268534255) + 0.19743823997123105))

## Decision boundary

A positive residual gain may replace V11 only if it passes the strict primary
validation and confirmation gates. A smaller gain may be retained as an
optional tail-risk research correction if it limits RMSE/P95 cost while
materially reducing P99 underprediction. Otherwise V11 remains the sole
deployable stress formula and V13 is reported as a non-deployed correction
study. No outcome in this notebook opens the final 50-case set.