# CT3: Integration of Four Frozen Rotations on 149 Development Cases

## Purpose

This notebook is the **development-integration stage**, not another symbolic search. It combines the four independently searched V10/V11 rotations after their structures have been frozen.

The procedure is deliberately conservative:

1. Every one of the 149 development cases remains complete; no element is sampled.
2. The four V10 stress formulae receive fixed equal weights of 0.25.
3. One compact case-mean correction is refitted on all 149 development cases.
4. Only V11 tail formulae that remain non-zero after complete-case centring enter the tail consensus. A constant tail therefore contributes nothing and is excluded.
5. One global tail gain is fitted with complete-element P90/P95/P99 weighting and constrained to the interval 0 to 1.
6. A predeclared gate selects the full tail model, the mean-only model, or the unmodified V10 consensus.

The 50 final-test cases are checked only for inventory, header and row count. Their predictor and stress values are not parsed or used. The output is a locked candidate that still requires explicit human review before the one-time final test.

In [1]:
from pathlib import Path
import json
import os
import sys

import pandas as pd

cwd = Path.cwd().resolve()
PACKAGE_ROOT = cwd.parent if cwd.name == "notebooks" else cwd
if PACKAGE_ROOT.name == "18_149Case_Development_Integration":
    PACKAGE_ROOT = PACKAGE_ROOT.parents[1]
SRC_DIR = PACKAGE_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

os.environ.setdefault("MPLCONFIGDIR", str(PACKAGE_ROOT / ".cache" / "matplotlib"))
Path(os.environ["MPLCONFIGDIR"]).mkdir(parents=True, exist_ok=True)

from final_development_integration import (
    DevelopmentIntegrationConfig,
    output_directory,
    preflight_development_integration,
    run_development_integration,
)

CONFIG = DevelopmentIntegrationConfig(
    output_subdir="formal_149case_integration",
    keep_case_cache_after_success=False,
    force_rebuild_case_cache=False,
)
OUTPUT_DIR = output_directory(PACKAGE_ROOT, CONFIG)

print("Package root:", PACKAGE_ROOT)
print("Output directory:", OUTPUT_DIR)
print("Final-test policy: inventory/header checks only; zero parsed predictor or stress rows")
print("Configuration:", CONFIG)

Package root: /net/scratch/j96317yn/NotebookCT3
Output directory: /net/scratch/j96317yn/NotebookCT3/outputs/18_149case_development_integration/formal_149case_integration
Final-test policy: inventory/header checks only; zero parsed predictor or stress rows
Configuration: DevelopmentIntegrationConfig(output_subdir='formal_149case_integration', tail_activity_std_threshold_mpa=1e-06, tail_gain_min=0.0, tail_gain_max=1.0, min_relative_rmse_improvement=0.0025, min_hotspot_overlap_gain=0.005, full_p99_ratio_to_mean_max=0.98, full_worst_rmse_ratio_to_mean_max=1.03, full_p95_ratio_to_base_max=1.2, mean_worst_rmse_ratio_to_base_max=1.05, mean_p99_ratio_to_base_max=1.25, mean_hotspot_drop_from_base_max=0.02, keep_case_cache_after_success=False, force_rebuild_case_cache=False)

## Preflight

Preflight checks all four completion chains, formula artifacts, the 149/50 frozen division, and the input hashes. It also confirms that Rotation 4 has a constant tail expression, which becomes exactly zero after complete-case centring.

In [2]:
preflight = preflight_development_integration(PACKAGE_ROOT, CONFIG)
display(preflight["checks"])
display(preflight["rotation_audit"])
print("Frozen input signature:", preflight["input_signature"])

                           check value expected  pass
0              development_cases   149      149  True
1             sealed_final_cases    50       50  True
2               frozen_rotations     4        4  True
3        constant_tail_rotations     1        1  True
4   iteration_4_tail_is_constant  True     True  True
5  final_test_element_files_read     0        0  True

,iteration,tail_complexity,tail_predictors,n_tail_predictors,symbolically_active,prior_selected_gain,prior_promotion_status
0,1,26,"nearest_angular_boundary_fraction_proxy,neares...",3,True,0.90,passes_all_v11_pilot_gates
1,2,21,"nearest_angular_boundary_fraction_proxy,neares...",2,True,0.75,diagnostic_only_does_not_pass_all_v11_pilot_gates
2,3,19,"nearest_angular_boundary_fraction_proxy,neares...",3,True,0.95,diagnostic_only_does_not_pass_all_v11_pilot_gates
3,4,1,,0,False,0.85,diagnostic_only_does_not_pass_all_v11_pilot_gates

Frozen input signature: bad8f0aa4debef330607994b4ddca48247080d1176c76592a485a066c165d7da

## Run or resume the 149-case integration

Each complete case is checkpointed after its four frozen symbolic predictions have been evaluated. If the scheduled job stops, submitting the same notebook again reuses valid case checkpoints. No PySR search is run here.

In [3]:
completion = run_development_integration(PACKAGE_ROOT, CONFIG)
display(pd.DataFrame([completion]))

[1/149] Development integration: case_01 (build checkpoint)

[2/149] Development integration: case_06 (build checkpoint)

[3/149] Development integration: case_10 (build checkpoint)

[4/149] Development integration: case_11 (build checkpoint)

[5/149] Development integration: case_12 (build checkpoint)

[6/149] Development integration: case_13 (build checkpoint)

[7/149] Development integration: case_14 (build checkpoint)

[8/149] Development integration: case_15 (build checkpoint)

[9/149] Development integration: case_16 (build checkpoint)

[10/149] Development integration: case_17 (build checkpoint)

[11/149] Development integration: case_18 (build checkpoint)

[12/149] Development integration: case_19 (build checkpoint)

[13/149] Development integration: case_20 (build checkpoint)

[14/149] Development integration: case_21 (build checkpoint)

[15/149] Development integration: case_24 (build checkpoint)

[16/149] Development integration: case_27 (build checkpoint)

[17/149] Development integration: case_28 (build checkpoint)

[18/149] Development integration: case_29 (build checkpoint)

[19/149] Development integration: case_32 (build checkpoint)

[20/149] Development integration: case_34 (build checkpoint)

[21/149] Development integration: case_35 (build checkpoint)

[22/149] Development integration: case_36 (build checkpoint)

[23/149] Development integration: case_39 (build checkpoint)

[24/149] Development integration: case_40 (build checkpoint)

[25/149] Development integration: case_42 (build checkpoint)

[26/149] Development integration: case_43 (build checkpoint)

[27/149] Development integration: case_44 (build checkpoint)

[28/149] Development integration: case_45 (build checkpoint)

[29/149] Development integration: case_47 (build checkpoint)

[30/149] Development integration: case_48 (build checkpoint)

[31/149] Development integration: case_49 (build checkpoint)

[32/149] Development integration: case_51 (build checkpoint)

[33/149] Development integration: case_52 (build checkpoint)

[34/149] Development integration: case_54 (build checkpoint)

[35/149] Development integration: case_56 (build checkpoint)

[36/149] Development integration: case_57 (build checkpoint)

[37/149] Development integration: case_58 (build checkpoint)

[38/149] Development integration: case_59 (build checkpoint)

[39/149] Development integration: case_60 (build checkpoint)

[40/149] Development integration: case_61 (build checkpoint)

[41/149] Development integration: case_62 (build checkpoint)

[42/149] Development integration: case_63 (build checkpoint)

[43/149] Development integration: case_64 (build checkpoint)

[44/149] Development integration: case_66 (build checkpoint)

[45/149] Development integration: case_67 (build checkpoint)

[46/149] Development integration: case_68 (build checkpoint)

[47/149] Development integration: case_69 (build checkpoint)

[48/149] Development integration: case_71 (build checkpoint)

[49/149] Development integration: case_72 (build checkpoint)

[50/149] Development integration: case_73 (build checkpoint)

[51/149] Development integration: case_74 (build checkpoint)

[52/149] Development integration: case_75 (build checkpoint)

[53/149] Development integration: case_77 (build checkpoint)

[54/149] Development integration: case_78 (build checkpoint)

[55/149] Development integration: case_79 (build checkpoint)

[56/149] Development integration: case_81 (build checkpoint)

[57/149] Development integration: case_82 (build checkpoint)

[58/149] Development integration: case_83 (build checkpoint)

[59/149] Development integration: case_84 (build checkpoint)

[60/149] Development integration: case_85 (build checkpoint)

[61/149] Development integration: case_86 (build checkpoint)

[62/149] Development integration: case_87 (build checkpoint)

[63/149] Development integration: case_89 (build checkpoint)

[64/149] Development integration: case_91 (build checkpoint)

[65/149] Development integration: case_92 (build checkpoint)

[66/149] Development integration: case_93 (build checkpoint)

[67/149] Development integration: case_94 (build checkpoint)

[68/149] Development integration: case_95 (build checkpoint)

[69/149] Development integration: case_96 (build checkpoint)

[70/149] Development integration: case_97 (build checkpoint)

[71/149] Development integration: case_98 (build checkpoint)

[72/149] Development integration: case_99 (build checkpoint)

[73/149] Development integration: case_100 (build checkpoint)

[74/149] Development integration: case_101 (build checkpoint)

[75/149] Development integration: case_102 (build checkpoint)

[76/149] Development integration: case_104 (build checkpoint)

[77/149] Development integration: case_105 (build checkpoint)

[78/149] Development integration: case_106 (build checkpoint)

[79/149] Development integration: case_107 (build checkpoint)

[80/149] Development integration: case_109 (build checkpoint)

[81/149] Development integration: case_110 (build checkpoint)

[82/149] Development integration: case_111 (build checkpoint)

[83/149] Development integration: case_114 (build checkpoint)

[84/149] Development integration: case_115 (build checkpoint)

[85/149] Development integration: case_116 (build checkpoint)

[86/149] Development integration: case_117 (build checkpoint)

[87/149] Development integration: case_118 (build checkpoint)

[88/149] Development integration: case_119 (build checkpoint)

[89/149] Development integration: case_120 (build checkpoint)

[90/149] Development integration: case_121 (build checkpoint)

[91/149] Development integration: case_122 (build checkpoint)

[92/149] Development integration: case_124 (build checkpoint)

[93/149] Development integration: case_125 (build checkpoint)

[94/149] Development integration: case_127 (build checkpoint)

[95/149] Development integration: case_128 (build checkpoint)

[96/149] Development integration: case_129 (build checkpoint)

[97/149] Development integration: case_130 (build checkpoint)

[98/149] Development integration: case_133 (build checkpoint)

[99/149] Development integration: case_136 (build checkpoint)

[100/149] Development integration: case_137 (build checkpoint)

[101/149] Development integration: case_139 (build checkpoint)

[102/149] Development integration: case_141 (build checkpoint)

[103/149] Development integration: case_142 (build checkpoint)

[104/149] Development integration: case_143 (build checkpoint)

[105/149] Development integration: case_144 (build checkpoint)

[106/149] Development integration: case_145 (build checkpoint)

[107/149] Development integration: case_146 (build checkpoint)

[108/149] Development integration: case_147 (build checkpoint)

[109/149] Development integration: case_148 (build checkpoint)

[110/149] Development integration: case_150 (build checkpoint)

[111/149] Development integration: case_151 (build checkpoint)

[112/149] Development integration: case_153 (build checkpoint)

[113/149] Development integration: case_154 (build checkpoint)

[114/149] Development integration: case_155 (build checkpoint)

[115/149] Development integration: case_156 (build checkpoint)

[116/149] Development integration: case_157 (build checkpoint)

[117/149] Development integration: case_158 (build checkpoint)

[118/149] Development integration: case_159 (build checkpoint)

[119/149] Development integration: case_163 (build checkpoint)

[120/149] Development integration: case_164 (build checkpoint)

[121/149] Development integration: case_165 (build checkpoint)

[122/149] Development integration: case_166 (build checkpoint)

[123/149] Development integration: case_169 (build checkpoint)

[124/149] Development integration: case_170 (build checkpoint)

[125/149] Development integration: case_171 (build checkpoint)

[126/149] Development integration: case_173 (build checkpoint)

[127/149] Development integration: case_175 (build checkpoint)

[128/149] Development integration: case_176 (build checkpoint)

[129/149] Development integration: case_179 (build checkpoint)

[130/149] Development integration: case_180 (build checkpoint)

[131/149] Development integration: case_181 (build checkpoint)

[132/149] Development integration: case_182 (build checkpoint)

[133/149] Development integration: case_183 (build checkpoint)

[134/149] Development integration: case_184 (build checkpoint)

[135/149] Development integration: case_185 (build checkpoint)

[136/149] Development integration: case_186 (build checkpoint)

[137/149] Development integration: case_187 (build checkpoint)

[138/149] Development integration: case_188 (build checkpoint)

[139/149] Development integration: case_189 (build checkpoint)

[140/149] Development integration: case_190 (build checkpoint)

[141/149] Development integration: case_191 (build checkpoint)

[142/149] Development integration: case_192 (build checkpoint)

[143/149] Development integration: case_193 (build checkpoint)

[144/149] Development integration: case_194 (build checkpoint)

[145/149] Development integration: case_195 (build checkpoint)

[146/149] Development integration: case_196 (build checkpoint)

[147/149] Development integration: case_197 (build checkpoint)

[148/149] Development integration: case_199 (build checkpoint)

[149/149] Development integration: case_200 (build checkpoint)

[1/149] Fit bounded tail gain: case_01

[2/149] Fit bounded tail gain: case_06

[3/149] Fit bounded tail gain: case_10

[4/149] Fit bounded tail gain: case_11

[5/149] Fit bounded tail gain: case_12

[6/149] Fit bounded tail gain: case_13

[7/149] Fit bounded tail gain: case_14

[8/149] Fit bounded tail gain: case_15

[9/149] Fit bounded tail gain: case_16

[10/149] Fit bounded tail gain: case_17

[11/149] Fit bounded tail gain: case_18

[12/149] Fit bounded tail gain: case_19

[13/149] Fit bounded tail gain: case_20

[14/149] Fit bounded tail gain: case_21

[15/149] Fit bounded tail gain: case_24

[16/149] Fit bounded tail gain: case_27

[17/149] Fit bounded tail gain: case_28

[18/149] Fit bounded tail gain: case_29

[19/149] Fit bounded tail gain: case_32

[20/149] Fit bounded tail gain: case_34

[21/149] Fit bounded tail gain: case_35

[22/149] Fit bounded tail gain: case_36

[23/149] Fit bounded tail gain: case_39

[24/149] Fit bounded tail gain: case_40

[25/149] Fit bounded tail gain: case_42

[26/149] Fit bounded tail gain: case_43

[27/149] Fit bounded tail gain: case_44

[28/149] Fit bounded tail gain: case_45

[29/149] Fit bounded tail gain: case_47

[30/149] Fit bounded tail gain: case_48

[31/149] Fit bounded tail gain: case_49

[32/149] Fit bounded tail gain: case_51

[33/149] Fit bounded tail gain: case_52

[34/149] Fit bounded tail gain: case_54

[35/149] Fit bounded tail gain: case_56

[36/149] Fit bounded tail gain: case_57

[37/149] Fit bounded tail gain: case_58

[38/149] Fit bounded tail gain: case_59

[39/149] Fit bounded tail gain: case_60

[40/149] Fit bounded tail gain: case_61

[41/149] Fit bounded tail gain: case_62

[42/149] Fit bounded tail gain: case_63

[43/149] Fit bounded tail gain: case_64

[44/149] Fit bounded tail gain: case_66

[45/149] Fit bounded tail gain: case_67

[46/149] Fit bounded tail gain: case_68

[47/149] Fit bounded tail gain: case_69

[48/149] Fit bounded tail gain: case_71

[49/149] Fit bounded tail gain: case_72

[50/149] Fit bounded tail gain: case_73

[51/149] Fit bounded tail gain: case_74

[52/149] Fit bounded tail gain: case_75

[53/149] Fit bounded tail gain: case_77

[54/149] Fit bounded tail gain: case_78

[55/149] Fit bounded tail gain: case_79

[56/149] Fit bounded tail gain: case_81

[57/149] Fit bounded tail gain: case_82

[58/149] Fit bounded tail gain: case_83

[59/149] Fit bounded tail gain: case_84

[60/149] Fit bounded tail gain: case_85

[61/149] Fit bounded tail gain: case_86

[62/149] Fit bounded tail gain: case_87

[63/149] Fit bounded tail gain: case_89

[64/149] Fit bounded tail gain: case_91

[65/149] Fit bounded tail gain: case_92

[66/149] Fit bounded tail gain: case_93

[67/149] Fit bounded tail gain: case_94

[68/149] Fit bounded tail gain: case_95

[69/149] Fit bounded tail gain: case_96

[70/149] Fit bounded tail gain: case_97

[71/149] Fit bounded tail gain: case_98

[72/149] Fit bounded tail gain: case_99

[73/149] Fit bounded tail gain: case_100

[74/149] Fit bounded tail gain: case_101

[75/149] Fit bounded tail gain: case_102

[76/149] Fit bounded tail gain: case_104

[77/149] Fit bounded tail gain: case_105

[78/149] Fit bounded tail gain: case_106

[79/149] Fit bounded tail gain: case_107

[80/149] Fit bounded tail gain: case_109

[81/149] Fit bounded tail gain: case_110

[82/149] Fit bounded tail gain: case_111

[83/149] Fit bounded tail gain: case_114

[84/149] Fit bounded tail gain: case_115

[85/149] Fit bounded tail gain: case_116

[86/149] Fit bounded tail gain: case_117

[87/149] Fit bounded tail gain: case_118

[88/149] Fit bounded tail gain: case_119

[89/149] Fit bounded tail gain: case_120

[90/149] Fit bounded tail gain: case_121

[91/149] Fit bounded tail gain: case_122

[92/149] Fit bounded tail gain: case_124

[93/149] Fit bounded tail gain: case_125

[94/149] Fit bounded tail gain: case_127

[95/149] Fit bounded tail gain: case_128

[96/149] Fit bounded tail gain: case_129

[97/149] Fit bounded tail gain: case_130

[98/149] Fit bounded tail gain: case_133

[99/149] Fit bounded tail gain: case_136

[100/149] Fit bounded tail gain: case_137

[101/149] Fit bounded tail gain: case_139

[102/149] Fit bounded tail gain: case_141

[103/149] Fit bounded tail gain: case_142

[104/149] Fit bounded tail gain: case_143

[105/149] Fit bounded tail gain: case_144

[106/149] Fit bounded tail gain: case_145

[107/149] Fit bounded tail gain: case_146

[108/149] Fit bounded tail gain: case_147

[109/149] Fit bounded tail gain: case_148

[110/149] Fit bounded tail gain: case_150

[111/149] Fit bounded tail gain: case_151

[112/149] Fit bounded tail gain: case_153

[113/149] Fit bounded tail gain: case_154

[114/149] Fit bounded tail gain: case_155

[115/149] Fit bounded tail gain: case_156

[116/149] Fit bounded tail gain: case_157

[117/149] Fit bounded tail gain: case_158

[118/149] Fit bounded tail gain: case_159

[119/149] Fit bounded tail gain: case_163

[120/149] Fit bounded tail gain: case_164

[121/149] Fit bounded tail gain: case_165

[122/149] Fit bounded tail gain: case_166

[123/149] Fit bounded tail gain: case_169

[124/149] Fit bounded tail gain: case_170

[125/149] Fit bounded tail gain: case_171

[126/149] Fit bounded tail gain: case_173

[127/149] Fit bounded tail gain: case_175

[128/149] Fit bounded tail gain: case_176

[129/149] Fit bounded tail gain: case_179

[130/149] Fit bounded tail gain: case_180

[131/149] Fit bounded tail gain: case_181

[132/149] Fit bounded tail gain: case_182

[133/149] Fit bounded tail gain: case_183

[134/149] Fit bounded tail gain: case_184

[135/149] Fit bounded tail gain: case_185

[136/149] Fit bounded tail gain: case_186

[137/149] Fit bounded tail gain: case_187

[138/149] Fit bounded tail gain: case_188

[139/149] Fit bounded tail gain: case_189

[140/149] Fit bounded tail gain: case_190

[141/149] Fit bounded tail gain: case_191

[142/149] Fit bounded tail gain: case_192

[143/149] Fit bounded tail gain: case_193

[144/149] Fit bounded tail gain: case_194

[145/149] Fit bounded tail gain: case_195

[146/149] Fit bounded tail gain: case_196

[147/149] Fit bounded tail gain: case_197

[148/149] Fit bounded tail gain: case_199

[149/149] Fit bounded tail gain: case_200

[1/149] Evaluate development candidates: case_01

[2/149] Evaluate development candidates: case_06

[3/149] Evaluate development candidates: case_10

[4/149] Evaluate development candidates: case_11

[5/149] Evaluate development candidates: case_12

[6/149] Evaluate development candidates: case_13

[7/149] Evaluate development candidates: case_14

[8/149] Evaluate development candidates: case_15

[9/149] Evaluate development candidates: case_16

[10/149] Evaluate development candidates: case_17

[11/149] Evaluate development candidates: case_18

[12/149] Evaluate development candidates: case_19

[13/149] Evaluate development candidates: case_20

[14/149] Evaluate development candidates: case_21

[15/149] Evaluate development candidates: case_24

[16/149] Evaluate development candidates: case_27

[17/149] Evaluate development candidates: case_28

[18/149] Evaluate development candidates: case_29

[19/149] Evaluate development candidates: case_32

[20/149] Evaluate development candidates: case_34

[21/149] Evaluate development candidates: case_35

[22/149] Evaluate development candidates: case_36

[23/149] Evaluate development candidates: case_39

[24/149] Evaluate development candidates: case_40

[25/149] Evaluate development candidates: case_42

[26/149] Evaluate development candidates: case_43

[27/149] Evaluate development candidates: case_44

[28/149] Evaluate development candidates: case_45

[29/149] Evaluate development candidates: case_47

[30/149] Evaluate development candidates: case_48

[31/149] Evaluate development candidates: case_49

[32/149] Evaluate development candidates: case_51

[33/149] Evaluate development candidates: case_52

[34/149] Evaluate development candidates: case_54

[35/149] Evaluate development candidates: case_56

[36/149] Evaluate development candidates: case_57

[37/149] Evaluate development candidates: case_58

[38/149] Evaluate development candidates: case_59

[39/149] Evaluate development candidates: case_60

[40/149] Evaluate development candidates: case_61

[41/149] Evaluate development candidates: case_62

[42/149] Evaluate development candidates: case_63

[43/149] Evaluate development candidates: case_64

[44/149] Evaluate development candidates: case_66

[45/149] Evaluate development candidates: case_67

[46/149] Evaluate development candidates: case_68

[47/149] Evaluate development candidates: case_69

[48/149] Evaluate development candidates: case_71

[49/149] Evaluate development candidates: case_72

[50/149] Evaluate development candidates: case_73

[51/149] Evaluate development candidates: case_74

[52/149] Evaluate development candidates: case_75

[53/149] Evaluate development candidates: case_77

[54/149] Evaluate development candidates: case_78

[55/149] Evaluate development candidates: case_79

[56/149] Evaluate development candidates: case_81

[57/149] Evaluate development candidates: case_82

[58/149] Evaluate development candidates: case_83

[59/149] Evaluate development candidates: case_84

[60/149] Evaluate development candidates: case_85

[61/149] Evaluate development candidates: case_86

[62/149] Evaluate development candidates: case_87

[63/149] Evaluate development candidates: case_89

[64/149] Evaluate development candidates: case_91

[65/149] Evaluate development candidates: case_92

[66/149] Evaluate development candidates: case_93

[67/149] Evaluate development candidates: case_94

[68/149] Evaluate development candidates: case_95

[69/149] Evaluate development candidates: case_96

[70/149] Evaluate development candidates: case_97

[71/149] Evaluate development candidates: case_98

[72/149] Evaluate development candidates: case_99

[73/149] Evaluate development candidates: case_100

[74/149] Evaluate development candidates: case_101

[75/149] Evaluate development candidates: case_102

[76/149] Evaluate development candidates: case_104

[77/149] Evaluate development candidates: case_105

[78/149] Evaluate development candidates: case_106

[79/149] Evaluate development candidates: case_107

[80/149] Evaluate development candidates: case_109

[81/149] Evaluate development candidates: case_110

[82/149] Evaluate development candidates: case_111

[83/149] Evaluate development candidates: case_114

[84/149] Evaluate development candidates: case_115

[85/149] Evaluate development candidates: case_116

[86/149] Evaluate development candidates: case_117

[87/149] Evaluate development candidates: case_118

[88/149] Evaluate development candidates: case_119

[89/149] Evaluate development candidates: case_120

[90/149] Evaluate development candidates: case_121

[91/149] Evaluate development candidates: case_122

[92/149] Evaluate development candidates: case_124

[93/149] Evaluate development candidates: case_125

[94/149] Evaluate development candidates: case_127

[95/149] Evaluate development candidates: case_128

[96/149] Evaluate development candidates: case_129

[97/149] Evaluate development candidates: case_130

[98/149] Evaluate development candidates: case_133

[99/149] Evaluate development candidates: case_136

[100/149] Evaluate development candidates: case_137

[101/149] Evaluate development candidates: case_139

[102/149] Evaluate development candidates: case_141

[103/149] Evaluate development candidates: case_142

[104/149] Evaluate development candidates: case_143

[105/149] Evaluate development candidates: case_144

[106/149] Evaluate development candidates: case_145

[107/149] Evaluate development candidates: case_146

[108/149] Evaluate development candidates: case_147

[109/149] Evaluate development candidates: case_148

[110/149] Evaluate development candidates: case_150

[111/149] Evaluate development candidates: case_151

[112/149] Evaluate development candidates: case_153

[113/149] Evaluate development candidates: case_154

[114/149] Evaluate development candidates: case_155

[115/149] Evaluate development candidates: case_156

[116/149] Evaluate development candidates: case_157

[117/149] Evaluate development candidates: case_158

[118/149] Evaluate development candidates: case_159

[119/149] Evaluate development candidates: case_163

[120/149] Evaluate development candidates: case_164

[121/149] Evaluate development candidates: case_165

[122/149] Evaluate development candidates: case_166

[123/149] Evaluate development candidates: case_169

[124/149] Evaluate development candidates: case_170

[125/149] Evaluate development candidates: case_171

[126/149] Evaluate development candidates: case_173

[127/149] Evaluate development candidates: case_175

[128/149] Evaluate development candidates: case_176

[129/149] Evaluate development candidates: case_179

[130/149] Evaluate development candidates: case_180

[131/149] Evaluate development candidates: case_181

[132/149] Evaluate development candidates: case_182

[133/149] Evaluate development candidates: case_183

[134/149] Evaluate development candidates: case_184

[135/149] Evaluate development candidates: case_185

[136/149] Evaluate development candidates: case_186

[137/149] Evaluate development candidates: case_187

[138/149] Evaluate development candidates: case_188

[139/149] Evaluate development candidates: case_189

[140/149] Evaluate development candidates: case_190

[141/149] Evaluate development candidates: case_191

[142/149] Evaluate development candidates: case_192

[143/149] Evaluate development candidates: case_193

[144/149] Evaluate development candidates: case_194

[145/149] Evaluate development candidates: case_195

[146/149] Evaluate development candidates: case_196

[147/149] Evaluate development candidates: case_197

[148/149] Evaluate development candidates: case_199

[149/149] Evaluate development candidates: case_200

,status,method,selected_model,development_cases,development_elements,sealed_final_cases,final_test_cases_read,active_tail_iterations,inactive_tail_iterations,tail_gain,input_signature_sha256,case_cache_retained,elapsed_seconds,output_directory
0,complete,four_rotation_consensus_refit_on_all_149_devel...,mean_calibrated_consensus,149,59653640,50,0,"[1, 2, 3]",[4],1.0,bad8f0aa4debef330607994b4ddca48247080d1176c765...,False,296.321743,/net/scratch/j96317yn/NotebookCT3/outputs/18_1...

## Locked result and audit

The table below is a **149-case fit diagnostic**. It is useful for checking whether the refit behaves as intended, but it is not an unbiased generalisation estimate because the mean coefficients and tail gain were fitted on these same development cases. The one-time 50-case result remains the only final performance statement.

In [4]:
summary = pd.read_csv(OUTPUT_DIR / "development_candidate_summary.csv")
activity = pd.read_csv(OUTPUT_DIR / "tail_activity_audit.csv")
decision = json.loads((OUTPUT_DIR / "final_model_decision.json").read_text())
release = json.loads((OUTPUT_DIR / "final_test_release_gate.json").read_text())

display(summary)
display(activity)
display(pd.DataFrame([{
    "selected_model": decision["selected_model"],
    "selection_reason": decision["selection_reason"],
    "active_tail_iterations": decision["active_tail_iterations"],
    "inactive_tail_iterations": decision["inactive_tail_iterations"],
    "final_test_cases_read": decision["final_test_cases_read"],
}]))
display(pd.DataFrame([release]))

print("\nLocked formula file:", OUTPUT_DIR / "locked_model_formula.txt")
print("\n" + (OUTPUT_DIR / "locked_model_formula.txt").read_text())

,split,model,n_cases,n_elements_evaluated,micro_mae,micro_rmse,micro_r2,macro_mae,macro_rmse,macro_r2,...,mean_top5_actual_rmse,mean_top5_actual_bias,mean_p95_relative_error,mean_p95_underprediction_fraction,mean_p99_relative_error,mean_p99_underprediction_fraction,mean_top5pct_hotspot_overlap,mean_top1pct_hotspot_overlap,mean_top1_recall_in_predicted_top5,max_prediction_abs_max_ratio
0,development_fit_diagnostic,v10_rotation_consensus,149,59653640,1.257532,1.803230,0.594553,1.257532,1.775980,0.536152,...,3.491832,-2.168616,0.040662,0.005171,0.161816,0.159931,0.506952,0.502446,0.833331,1.379245
1,development_fit_diagnostic,mean_calibrated_consensus,149,59653640,1.209951,1.730131,0.626758,1.209951,1.702666,0.579579,...,3.810334,-2.666536,0.046034,0.038286,0.196972,0.196722,0.506952,0.502446,0.833331,1.345167
2,development_fit_diagnostic,full_consensus_tail,149,59653640,1.196720,1.662854,0.655222,1.196720,1.632616,0.610523,...,3.108399,-1.859556,0.037691,0.005882,0.161972,0.160999,0.576571,0.569109,0.934534,1.425297
3,development_fit_diagnostic,frozen_rotation_selected_ensemble,149,59653640,1.195876,1.671340,0.651694,1.195876,1.642657,0.607245,...,3.374877,-2.216641,0.035857,0.021635,0.183106,0.182709,0.554997,0.548519,0.889421,1.390625

,iteration,tail_complexity,tail_predictors,symbolically_active,mean_complete_case_tail_std_mpa,max_complete_case_tail_std_mpa,numerically_active,included_in_tail_consensus,prior_selected_gain,interpretation
0,1,26,"nearest_angular_boundary_fraction_proxy,neares...",True,7.969025e-01,1.334105e+00,True,True,0.90,active spatial tail formula
1,2,21,"nearest_angular_boundary_fraction_proxy,neares...",True,8.424940e-01,1.406946e+00,True,True,0.75,active spatial tail formula
2,3,19,"nearest_angular_boundary_fraction_proxy,neares...",True,6.265896e-01,1.044764e+00,True,True,0.95,active spatial tail formula
3,4,1,NaN,False,7.478295e-32,2.958228e-31,False,False,0.85,constant or numerically zero after complete-ca...

,selected_model,selection_reason,active_tail_iterations,inactive_tail_iterations,final_test_cases_read
0,mean_calibrated_consensus,Tail consensus failed at least one gate; the s...,"[1, 2, 3]",[4],0

,technical_status,locked_model_exists,locked_model,final_test_has_been_opened,final_test_cases_read,human_approval_required,approved,next_stage
0,ready_for_human_review_before_one_time_final_test,True,mean_calibrated_consensus,False,0,True,False,"review diagnostics, then create a separate one..."

Locked formula file: /net/scratch/j96317yn/NotebookCT3/outputs/18_149case_development_integration/formal_149case_integration/locked_model_formula.txt

CT3 locked 149-case development formula
=======================================

IMPORTANT: This formula has not yet been evaluated on the sealed 50-case final test.
The 149-case metrics are fit diagnostics, not an unbiased generalisation estimate.

Locked model: mean_calibrated_consensus
Active tail rotations: [1, 2, 3]
Inactive tail rotations: [4]

1. Equal-weight V10 rotation consensus
(1/4) * (((-0.0116301024532845*temperature_mean + 0.0470427355318997*temperature_p95 - 3.16087946558646*weight_loss_rate_mean + 0.103449215368151*z_max - 0.870195660324862*Abs(4.60760803334225*fluence_rate_p95 - 20.3572633494299) - 100.195330145459) + exp(-1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276) * ((1.10317833861391*(0.55673575*(0.0509611749551904*rho - 9.32241465638866)*(0.0509611749551904*rho - 8.66867535638866) - 31.9731949759449*(theta_cos - 0.922666019258146)**2)*(Abs(0.0509611749551904*rho - 8.59575422638866) - 2.4201684) + 0.285739561816426) + (0.0005298607274781943*z + 0.17657582192765694*(6.3559467282562*nearest_axial_boundary_fraction_proxy - 1.50570424883607)*(-7.28799975835273*nearest_radial_boundary_fraction_proxy + 0.0517386902634747*rho - 6.047025771972898) - 0.24332347927944745 + 0.793705512144892*exp(-9.5925971595468041*(6.3559467282562*nearest_axial_boundary_fraction_proxy - 0.043846887113135693)**2)) + (0.687707530043104*(3.752650699651312*nearest_angular_boundary_fraction_proxy + 7.28799975835273*nearest_radial_boundary_fraction_proxy - 3.560078810528026 + 0.2777422381074965)*(-0.44608657163711589*fluence_rate_mean - 1.291571739959816*nearest_angular_boundary_fraction_proxy + 0.66354475675260838*theta_fraction_proxy + 0.14984744098602391*Abs(-7.28799975835273*nearest_radial_boundary_fraction_proxy + 2.40848321928096*signed_radial_position_proxy + 2.08439162588874) - 0.07467188916362873 + 1.6933224087437673) + 0.0275995197448158))) + ((-0.0116301024532845*temperature_mean + 0.0470427355318997*temperature_p95 - 3.16087946558646*weight_loss_rate_mean + 0.103449215368151*z_max - 0.870195660324862*Abs(4.60760803334225*fluence_rate_p95 - 20.3572633494299) - 100.195330145459) + exp(-1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276) * ((1.10317833861391*(0.55673575*(0.0509611749551904*rho - 9.32241465638866)*(0.0509611749551904*rho - 8.66867535638866) - 31.9731949759449*(theta_cos - 0.922666019258146)**2)*(Abs(0.0509611749551904*rho - 8.59575422638866) - 2.4201684) + 0.285739561816426) + (0.013448561903935085*rho + 0.47728387820325316*z_fraction_proxy - 0.14564637922329544*(4.12918244017469*radial_axial_signed_interaction_proxy - 0.0672749794120767)**2 - 0.25957527828470824*(3.27700476145386*z_fraction_proxy - 1.74794266617586)**2*(43.6667583874302*boundary_corner_proximity_proxy + 2.41221284098931*signed_radial_position_proxy - 1.33262514125946) - 2.5544146883819192) + (-0.30554813835799807*(-3.21657514159445*nearest_axial_boundary_fraction_proxy + 7.28302970000392*nearest_radial_boundary_fraction_proxy + 0.74873754155936657*(15.6006536140747*theta_cos - 14.4099430342809)**2 - 1.64538465194802)*exp(-(7.28302970000392*nearest_radial_boundary_fraction_proxy - 1.692628259533093)**2) + 0.0182360501390777))) + ((-0.0116301024532845*temperature_mean + 0.0470427355318997*temperature_p95 - 3.16087946558646*weight_loss_rate_mean + 0.103449215368151*z_max - 0.870195660324862*Abs(4.60760803334225*fluence_rate_p95 - 20.3572633494299) - 100.195330145459) + exp(-1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276) * ((1.10317833861391*(0.55673575*(0.0509611749551904*rho - 9.32241465638866)*(0.0509611749551904*rho - 8.66867535638866) - 31.9731949759449*(theta_cos - 0.922666019258146)**2)*(Abs(0.0509611749551904*rho - 8.59575422638866) - 2.4201684) + 0.285739561816426) + (0.2037571042198979*(6.34896758686985*nearest_axial_boundary_fraction_proxy - 1.50273900081816)*(-7.28718952316989*nearest_radial_boundary_fraction_proxy + 4.82379391683032*rho_fraction_proxy + (6.34896758686985*nearest_axial_boundary_fraction_proxy - 1.50273900081816)*(4.979166764659604*nearest_radial_boundary_fraction_proxy - 0.7555397874783048) - 0.33238851694632) + 0.2037571042198979*tanh(0.953329938170801*z_within_case_z - 0.107660433093972) - 0.05430264797518295) + (-0.1031611420170622*(2.88495936431966*fluence_rate_mean - 10.3023995474472)*(7.28718952316989*nearest_radial_boundary_fraction_proxy - 2.40757030907997) + 0.0171984021271988))) + ((-0.0116301024532845*temperature_mean + 0.0470427355318997*temperature_p95 - 3.16087946558646*weight_loss_rate_mean + 0.103449215368151*z_max - 0.870195660324862*Abs(4.60760803334225*fluence_rate_p95 - 20.3572633494299) - 100.195330145459) + exp(-1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276) * ((1.10317833861391*(0.55673575*(0.0509611749551904*rho - 9.32241465638866)*(0.0509611749551904*rho - 8.66867535638866) - 31.9731949759449*(theta_cos - 0.922666019258146)**2)*(Abs(0.0509611749551904*rho - 8.59575422638866) - 2.4201684) + 0.285739561816426) + (0.26613534581272986*signed_axial_position_proxy - 0.1622288885733871*(6.35717263336409*nearest_axial_boundary_fraction_proxy - 1.50609073609435)*(-7.0761696316530864*nearest_axial_boundary_fraction_proxy + 7.2459763106469*nearest_radial_boundary_fraction_proxy - 0.069780171113859076*rho - (6.35717263336409*nearest_axial_boundary_fraction_proxy - 1.50609073609435)*(7.2459763106469*nearest_radial_boundary_fraction_proxy - 2.38325249598573) + 12.075351442964397) - 0.1622288885733871*Abs(7.94873136269381*nearest_angular_boundary_fraction_proxy + 7.2459763106469*nearest_radial_boundary_fraction_proxy - 2.21701884243319*signed_angular_position_proxy - 4.509683458131166) + 0.13991710730167015) + (-0.10412130908674733*(7.2459763106469*nearest_radial_boundary_fraction_proxy - 2.38325249598573)*(2.63391439710955*fluence_rate_mean + (43.826976828009*boundary_corner_proximity_proxy - 1.00232009854836)*(2.40096813285283*signed_radial_position_proxy + 0.381717477146586) - 9.50597278012606) + 0.0296437391158275))))

2. Mean correction refitted on all 149 development cases
(0.2268228967706677) + (-0.05934540474157227)*fluence_rate_mean + (-0.06916670716381103)*fluence_rate_p95 + (-0.0001424365280890297)*temperature_mean + (-0.001154704691824341)*temperature_p95 + (0.1042784929421962)*weight_loss_rate_mean + (5.748350348925075)*weight_loss_rate_std

3. Active V11 tail consensus
(1/3) * (exp(-1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276) * ((1.2093601333202474*(-0.16122678679851166 + exp(-92.749309109240237*(0.3382200152451777 - 2.08887119255503*signed_angular_position_proxy)**2))*(7.68957066477673*nearest_angular_boundary_fraction_proxy - 2.27807624632193)*(7.38407920683658*nearest_radial_boundary_fraction_proxy + Abs(7.38407920683658*nearest_radial_boundary_fraction_proxy - 2.57458268534255) - 2.57458268534255) + 0.19743823997123105) - case_mean(1.2093601333202474*(-0.16122678679851166 + exp(-92.749309109240237*(0.3382200152451777 - 2.08887119255503*signed_angular_position_proxy)**2))*(7.68957066477673*nearest_angular_boundary_fraction_proxy - 2.27807624632193)*(7.38407920683658*nearest_radial_boundary_fraction_proxy + Abs(7.38407920683658*nearest_radial_boundary_fraction_proxy - 2.57458268534255) - 2.57458268534255) + 0.19743823997123105)) + exp(-1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276) * ((-0.7395130863147979*nearest_angular_boundary_fraction_proxy - 0.5659502749777386*tanh(0.5353280385268686 - 0.1308541133824969/(3.416326193660334 - 7.38936236032781*nearest_radial_boundary_fraction_proxy)) + 0.7048825072967699) - case_mean(-0.7395130863147979*nearest_angular_boundary_fraction_proxy - 0.5659502749777386*tanh(0.5353280385268686 - 0.1308541133824969/(3.416326193660334 - 7.38936236032781*nearest_radial_boundary_fraction_proxy)) + 0.7048825072967699)) + exp(-1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276) * ((-0.14658512288138305*(2.09089288702877*signed_angular_position_proxy + 0.137695505370236)*(-7.71320426068593*nearest_angular_boundary_fraction_proxy - (2.09089288702877*signed_angular_position_proxy + 0.137695505370236)*tanh(17.18609187709957*nearest_radial_boundary_fraction_proxy - 6.015348714070041) + 1.40911851509649) + 0.25775031369935591) - case_mean(-0.14658512288138305*(2.09089288702877*signed_angular_position_proxy + 0.137695505370236)*(-7.71320426068593*nearest_angular_boundary_fraction_proxy - (2.09089288702877*signed_angular_position_proxy + 0.137695505370236)*tanh(17.18609187709957*nearest_radial_boundary_fraction_proxy - 6.015348714070041) + 1.40911851509649) + 0.25775031369935591)))

4. Bounded all-development tail gain = 1

5. Locked deployable expression
((1/4) * (((-0.0116301024532845*temperature_mean + 0.0470427355318997*temperature_p95 - 3.16087946558646*weight_loss_rate_mean + 0.103449215368151*z_max - 0.870195660324862*Abs(4.60760803334225*fluence_rate_p95 - 20.3572633494299) - 100.195330145459) + exp(-1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276) * ((1.10317833861391*(0.55673575*(0.0509611749551904*rho - 9.32241465638866)*(0.0509611749551904*rho - 8.66867535638866) - 31.9731949759449*(theta_cos - 0.922666019258146)**2)*(Abs(0.0509611749551904*rho - 8.59575422638866) - 2.4201684) + 0.285739561816426) + (0.0005298607274781943*z + 0.17657582192765694*(6.3559467282562*nearest_axial_boundary_fraction_proxy - 1.50570424883607)*(-7.28799975835273*nearest_radial_boundary_fraction_proxy + 0.0517386902634747*rho - 6.047025771972898) - 0.24332347927944745 + 0.793705512144892*exp(-9.5925971595468041*(6.3559467282562*nearest_axial_boundary_fraction_proxy - 0.043846887113135693)**2)) + (0.687707530043104*(3.752650699651312*nearest_angular_boundary_fraction_proxy + 7.28799975835273*nearest_radial_boundary_fraction_proxy - 3.560078810528026 + 0.2777422381074965)*(-0.44608657163711589*fluence_rate_mean - 1.291571739959816*nearest_angular_boundary_fraction_proxy + 0.66354475675260838*theta_fraction_proxy + 0.14984744098602391*Abs(-7.28799975835273*nearest_radial_boundary_fraction_proxy + 2.40848321928096*signed_radial_position_proxy + 2.08439162588874) - 0.07467188916362873 + 1.6933224087437673) + 0.0275995197448158))) + ((-0.0116301024532845*temperature_mean + 0.0470427355318997*temperature_p95 - 3.16087946558646*weight_loss_rate_mean + 0.103449215368151*z_max - 0.870195660324862*Abs(4.60760803334225*fluence_rate_p95 - 20.3572633494299) - 100.195330145459) + exp(-1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276) * ((1.10317833861391*(0.55673575*(0.0509611749551904*rho - 9.32241465638866)*(0.0509611749551904*rho - 8.66867535638866) - 31.9731949759449*(theta_cos - 0.922666019258146)**2)*(Abs(0.0509611749551904*rho - 8.59575422638866) - 2.4201684) + 0.285739561816426) + (0.013448561903935085*rho + 0.47728387820325316*z_fraction_proxy - 0.14564637922329544*(4.12918244017469*radial_axial_signed_interaction_proxy - 0.0672749794120767)**2 - 0.25957527828470824*(3.27700476145386*z_fraction_proxy - 1.74794266617586)**2*(43.6667583874302*boundary_corner_proximity_proxy + 2.41221284098931*signed_radial_position_proxy - 1.33262514125946) - 2.5544146883819192) + (-0.30554813835799807*(-3.21657514159445*nearest_axial_boundary_fraction_proxy + 7.28302970000392*nearest_radial_boundary_fraction_proxy + 0.74873754155936657*(15.6006536140747*theta_cos - 14.4099430342809)**2 - 1.64538465194802)*exp(-(7.28302970000392*nearest_radial_boundary_fraction_proxy - 1.692628259533093)**2) + 0.0182360501390777))) + ((-0.0116301024532845*temperature_mean + 0.0470427355318997*temperature_p95 - 3.16087946558646*weight_loss_rate_mean + 0.103449215368151*z_max - 0.870195660324862*Abs(4.60760803334225*fluence_rate_p95 - 20.3572633494299) - 100.195330145459) + exp(-1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276) * ((1.10317833861391*(0.55673575*(0.0509611749551904*rho - 9.32241465638866)*(0.0509611749551904*rho - 8.66867535638866) - 31.9731949759449*(theta_cos - 0.922666019258146)**2)*(Abs(0.0509611749551904*rho - 8.59575422638866) - 2.4201684) + 0.285739561816426) + (0.2037571042198979*(6.34896758686985*nearest_axial_boundary_fraction_proxy - 1.50273900081816)*(-7.28718952316989*nearest_radial_boundary_fraction_proxy + 4.82379391683032*rho_fraction_proxy + (6.34896758686985*nearest_axial_boundary_fraction_proxy - 1.50273900081816)*(4.979166764659604*nearest_radial_boundary_fraction_proxy - 0.7555397874783048) - 0.33238851694632) + 0.2037571042198979*tanh(0.953329938170801*z_within_case_z - 0.107660433093972) - 0.05430264797518295) + (-0.1031611420170622*(2.88495936431966*fluence_rate_mean - 10.3023995474472)*(7.28718952316989*nearest_radial_boundary_fraction_proxy - 2.40757030907997) + 0.0171984021271988))) + ((-0.0116301024532845*temperature_mean + 0.0470427355318997*temperature_p95 - 3.16087946558646*weight_loss_rate_mean + 0.103449215368151*z_max - 0.870195660324862*Abs(4.60760803334225*fluence_rate_p95 - 20.3572633494299) - 100.195330145459) + exp(-1.47091131932291*rho_mean - 1011.416708227*theta_sin_std - 1.1690770556861*weight_loss_rate_mean + 0.904578545888617*z_mean + 9.23869712445276) * ((1.10317833861391*(0.55673575*(0.0509611749551904*rho - 9.32241465638866)*(0.0509611749551904*rho - 8.66867535638866) - 31.9731949759449*(theta_cos - 0.922666019258146)**2)*(Abs(0.0509611749551904*rho - 8.59575422638866) - 2.4201684) + 0.285739561816426) + (0.26613534581272986*signed_axial_position_proxy - 0.1622288885733871*(6.35717263336409*nearest_axial_boundary_fraction_proxy - 1.50609073609435)*(-7.0761696316530864*nearest_axial_boundary_fraction_proxy + 7.2459763106469*nearest_radial_boundary_fraction_proxy - 0.069780171113859076*rho - (6.35717263336409*nearest_axial_boundary_fraction_proxy - 1.50609073609435)*(7.2459763106469*nearest_radial_boundary_fraction_proxy - 2.38325249598573) + 12.075351442964397) - 0.1622288885733871*Abs(7.94873136269381*nearest_angular_boundary_fraction_proxy + 7.2459763106469*nearest_radial_boundary_fraction_proxy - 2.21701884243319*signed_angular_position_proxy - 4.509683458131166) + 0.13991710730167015) + (-0.10412130908674733*(7.2459763106469*nearest_radial_boundary_fraction_proxy - 2.38325249598573)*(2.63391439710955*fluence_rate_mean + (43.826976828009*boundary_corner_proximity_proxy - 1.00232009854836)*(2.40096813285283*signed_radial_position_proxy + 0.381717477146586) - 9.50597278012606) + 0.0296437391158275))))) + ((0.2268228967706677) + (-0.05934540474157227)*fluence_rate_mean + (-0.06916670716381103)*fluence_rate_p95 + (-0.0001424365280890297)*temperature_mean + (-0.001154704691824341)*temperature_p95 + (0.1042784929421962)*weight_loss_rate_mean + (5.748350348925075)*weight_loss_rate_std)

All case_mean(...) terms are calculated from predictor-only values inside the new case.
No measured or FEM-computed stress summary is required at deployment.